In [ ]:
import pandas as pd
import numpy as np
import seaborn as srn
import matplotlib.pyplot as plt

In [2]:
from charset_normalizer import from_path
caminho = "../data/raw/Superstore.csv"
resultado = from_path(caminho).best()
encoding_detectado = resultado.encoding
confianca = resultado.coherence
print(encoding_detectado)
print(confianca)

cp1250
0.7082

In [4]:
df = pd.read_csv("../data/raw/Superstore.csv", encoding= 'cp1250')

In [6]:
df.shape

(9994, 21)

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [11]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

# Objetivo Prever o lucro esperado de uma transação a partir das características comerciais conhecidas da venda.

In [12]:
df["Country"].value_counts()

Country
United States    9994
Name: count, dtype: int64

In [ ]:
df.nunique() #valores únicos de todas as colunas

Row ID           9994
Order ID         5009
Order Date       1238
Ship Date        1334
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              531
State              49
Postal Code       631
Region              4
Product ID       1862
Category            3
Sub-Category       17
Product Name     1841
Sales            5825
Quantity           14
Discount           12
Profit           7287
dtype: int64

In [14]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [15]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].corr()

             Sales  Quantity  Discount    Profit
Sales     1.000000  0.200795 -0.028190  0.479064
Quantity  0.200795  1.000000  0.008623  0.066253
Discount -0.028190  0.008623  1.000000 -0.219487
Profit    0.479064  0.066253 -0.219487  1.000000

In [18]:
features = [
    "Ship Mode",
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Sales',
    'Quantity',
    'Discount'
    ] 

target =  'Profit'

In [22]:
X = df[features] # variáveis independentes/preditoras
y = df[target] #variável dependente/alvo

In [24]:
X.shape
y.shape

(9994,)

#### Separação de features por tipo

In [25]:
features_numericas = [
    'Sales',
    'Quantity',
    'Discount'
]

features_categoricas = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

In [ ]:
print(X.head())
print(X.shape)
print(y.head()) 
print(y.shape) 
print(X.dtypes)

        Ship Mode    Segment Region         Category Sub-Category     Sales  \
0    Second Class   Consumer  South        Furniture    Bookcases  261.9600
1    Second Class   Consumer  South        Furniture       Chairs  731.9400
2    Second Class  Corporate   West  Office Supplies       Labels   14.6200
3  Standard Class   Consumer  South        Furniture       Tables  957.5775
4  Standard Class   Consumer  South  Office Supplies      Storage   22.3680

   Quantity  Discount
0         2      0.00
1         3      0.00
2         2      0.00
3         5      0.45
4         2      0.20
(9994, 8)
0     41.9136
1    219.5820
2      6.8714
3   -383.0310
4      2.5164
Name: Profit, dtype: float64
(9994,)
Ship Mode           str
Segment             str
Region              str
Category            str
Sub-Category        str
Sales           float64
Quantity          int64
Discount        float64
dtype: object

#### Importação de bibliotecas scikit-learn > train_test_split

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
# 
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [32]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (7995, 8)
X_test: (1999, 8)
y_train: (7995,)
y_test: (1999,)

In [33]:
X_train['Segment'].unique()

<StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

#### Criação do One_hot_encoder

In [36]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

features_numericas = [
    'Sales',
    'Quantity',
    'Discount'
]

features_categoricas = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

encoder = OneHotEncoder(
    handle_unknown='ignore'
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            encoder,
            features_categoricas
        )
    ],
    remainder='passthrough'
)

In [37]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Ship Mode', 'Segment', 'Region', 'Category',
                                  'Sub-Category'])])

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

modelo_lr = LinearRegression()

pipeline_lr = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_lr)
    ]
)

pipeline_lr.fit(X_train, y_train)

y_pred_lr = pipeline_lr.predict(X_test)

In [39]:
print(y_pred_lr[:10])

[  79.03485168   36.24686833   55.75657935  -51.62315952 -153.79443364
    1.41577812  -14.23549172   95.41024948  -80.36007001  -69.61534619]

In [40]:
comparacao = pd.DataFrame({
    'Profit Real': y_test.values,
    'Profit Previsto': y_pred_lr
})

comparacao.head(10)

   Profit Real  Profit Previsto
0      21.1428        79.034852
1      11.4600        36.246868
2      17.1580        55.756579
3     -15.1470       -51.623160
4      -6.4233      -153.794434
5       8.6744         1.415778
6     -73.7061       -14.235492
7       8.6900        95.410249
8     -15.0800       -80.360070
9      17.9080       -69.615346

In [41]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [43]:
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"MAE:  {mae_lr:.2f}")
print(f"RMSE: {rmse_lr:.2f}")
print(f"R²:   {r2_lr:.4f}")

print()
print(f"Média Profit teste:   {y_test.mean():.2f}")
print(f"Mediana Profit teste: {y_test.median():.2f}")
print(f"Desvio padrão:        {y_test.std():.2f}")

MAE:  67.76
RMSE: 282.51
R²:   -0.6461

Média Profit teste:   20.50
Mediana Profit teste: 8.69
Desvio padrão:        220.25