In [37]:
import pandas as pd
import numpy as np
import seaborn as srn
import matplotlib.pyplot as plt

In [38]:
from charset_normalizer import from_path
caminho = "../data/raw/Superstore.csv"
resultado = from_path(caminho).best()
encoding_detectado = resultado.encoding
confianca = resultado.coherence
print(encoding_detectado)
print(confianca)

cp1250
0.7082

In [39]:
df = pd.read_csv("../data/raw/Superstore.csv", encoding= 'cp1250')

In [40]:
df.shape

(9994, 21)

In [41]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [43]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

# Objetivo Prever o lucro esperado de uma transação a partir das características comerciais conhecidas da venda.

In [44]:
df["Country"].value_counts()

Country
United States    9994
Name: count, dtype: int64

In [45]:
df.nunique() #valores únicos de todas as colunas

Row ID           9994
Order ID         5009
Order Date       1238
Ship Date        1334
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              531
State              49
Postal Code       631
Region              4
Product ID       1862
Category            3
Sub-Category       17
Product Name     1841
Sales            5825
Quantity           14
Discount           12
Profit           7287
dtype: int64

In [46]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [47]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].corr()

             Sales  Quantity  Discount    Profit
Sales     1.000000  0.200795 -0.028190  0.479064
Quantity  0.200795  1.000000  0.008623  0.066253
Discount -0.028190  0.008623  1.000000 -0.219487
Profit    0.479064  0.066253 -0.219487  1.000000

In [48]:
features = [
    "Ship Mode",
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Sales',
    'Quantity',
    'Discount'
    ] 

target =  'Profit'

In [49]:
X = df[features] # variáveis independentes/preditoras
y = df[target] #variável dependente/alvo

In [50]:
X.shape
y.shape

(9994,)

#### Separação de features por tipo

In [51]:
features_numericas = [
    'Sales',
    'Quantity',
    'Discount'
]

features_categoricas = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

In [52]:
print(X.head())
print(X.shape)
print(y.head()) 
print(y.shape) 
print(X.dtypes)

        Ship Mode    Segment Region         Category Sub-Category     Sales  \
0    Second Class   Consumer  South        Furniture    Bookcases  261.9600
1    Second Class   Consumer  South        Furniture       Chairs  731.9400
2    Second Class  Corporate   West  Office Supplies       Labels   14.6200
3  Standard Class   Consumer  South        Furniture       Tables  957.5775
4  Standard Class   Consumer  South  Office Supplies      Storage   22.3680

   Quantity  Discount
0         2      0.00
1         3      0.00
2         2      0.00
3         5      0.45
4         2      0.20
(9994, 8)
0     41.9136
1    219.5820
2      6.8714
3   -383.0310
4      2.5164
Name: Profit, dtype: float64
(9994,)
Ship Mode        object
Segment          object
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
dtype: object

#### Importação de bibliotecas scikit-learn > train_test_split

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
# 
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [55]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (7995, 8)
X_test: (1999, 8)
y_train: (7995,)
y_test: (1999,)

In [56]:
X_train['Segment'].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

#### Criação do One_hot_encoder

In [57]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

features_numericas = [
    'Sales',
    'Quantity',
    'Discount'
]

features_categoricas = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

encoder = OneHotEncoder(
    handle_unknown='ignore'
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            encoder,
            features_categoricas
        )
    ],
    remainder='passthrough'
)

In [58]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Ship Mode', 'Segment', 'Region', 'Category',
                                  'Sub-Category'])])

In [59]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

modelo_lr = LinearRegression()

pipeline_lr = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_lr)
    ]
)

pipeline_lr.fit(X_train, y_train)

y_pred_lr = pipeline_lr.predict(X_test)

In [60]:
print(y_pred_lr[:10])

[  79.03485168   36.24686834   55.75657936  -51.62315952 -153.79443364
    1.41577812  -14.23549171   95.41024949  -80.36007     -69.61534622]

In [61]:
comparacao = pd.DataFrame({
    'Profit Real': y_test.values,
    'Profit Previsto': y_pred_lr
})

comparacao.head(10)

   Profit Real  Profit Previsto
0      21.1428        79.034852
1      11.4600        36.246868
2      17.1580        55.756579
3     -15.1470       -51.623160
4      -6.4233      -153.794434
5       8.6744         1.415778
6     -73.7061       -14.235492
7       8.6900        95.410249
8     -15.0800       -80.360070
9      17.9080       -69.615346

In [62]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [63]:
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"MAE:  {mae_lr:.2f}")
print(f"RMSE: {rmse_lr:.2f}")
print(f"R²:   {r2_lr:.4f}")

print()
print(f"Média Profit teste:   {y_test.mean():.2f}")
print(f"Mediana Profit teste: {y_test.median():.2f}")
print(f"Desvio padrão:        {y_test.std():.2f}")

MAE:  67.76
RMSE: 282.51
R²:   -0.6461

Média Profit teste:   20.50
Mediana Profit teste: 8.69
Desvio padrão:        220.25

In [64]:
from visualizacao.resultado import calcular_metricas_regressao
from modelagem.metricas import registrar_resultado

In [65]:
resultados = pd.DataFrame()

In [66]:
resultados = pd.DataFrame()

metricas_Lr = calcular_metricas_regressao(y_test, y_pred_lr)

In [67]:
resultados = registrar_resultado(resultados, 'Regressão Linear', metricas_Lr)

In [68]:
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.50,8.69,220.25

#### Arvore de decisão

In [69]:
# Importação da biblioteca DecisionTreeRegressor do scikit-learn
from sklearn.tree import DecisionTreeRegressor

In [70]:
# modelo sem poda explicita, avaliação de overfitting, sem regularização, sem poda, sem limite de profundidade, sem limite de folhas, sem limite de amostras mínimas por folha
modelo_dt = DecisionTreeRegressor(random_state=42)

#Criação do pipeline para o modelo de árvore de decisão
pipeline_dt = Pipeline(
    steps=[
        ('processor', preprocessor),
        ('modelo', modelo_dt)
    ]
)

In [71]:
# Treinamento do modelo de árvore de decisão
pipeline_dt.fit(X_train, y_train)

Pipeline(steps=[('processor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo', DecisionTreeRegressor(random_state=42))])

In [72]:
# Previsão dos valores de Profit para o conjunto de teste usando o modelo de árvore de decisão
y_pred_dt_train = pipeline_dt.predict(X_train)
y_pred_dt = pipeline_dt.predict(X_test)
# Métricas
metricas_dt_train = calcular_metricas_regressao(
    y_train,
    y_pred_dt_train
)
resultados = registrar_resultado(
    resultados,
    "Decision Tree _ train",
    metricas_dt_train
)
metricas_dt = calcular_metricas_regressao(
    y_test,
    y_pred_dt
)
resultados = registrar_resultado(
    resultados,
    "Decision Tree test",
    metricas_dt
)
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.50,8.69,220.25
1,Decision Tree _ train,0.055392,0.911667,0.954812,0.999984,30.70,8.64,237.60
2,Decision Tree test,34.614556,81762.376829,285.941212,-0.686339,20.50,8.69,220.25

In [73]:
# Modelo com profundidade máxima dentro de uma variavel com um for, sem limite de folhas, sem limite de amostras mínimas por folha
profundidades = [2, 3, 5, 7, 10, 15, 20]
resultados_profundidade = []

for profundidade in profundidades:

    modelo = DecisionTreeRegressor(
        max_depth=profundidade,
        random_state=42
    )

    pipeline = Pipeline(
        steps=[
            ('preprocessor', preprocessor),
            ('modelo', modelo)
        ]
    )

    pipeline.fit(X_train, y_train)

    pred_train = pipeline.predict(X_train)
    pred_test = pipeline.predict(X_test)

    metricas_train = calcular_metricas_regressao(
        y_train,
        pred_train
    )

    metricas_test = calcular_metricas_regressao(
        y_test,
        pred_test
    )

    resultados_profundidade.append({
        'max_depth': profundidade,

        'MAE treino': metricas_train['MAE'],
        'MAE teste': metricas_test['MAE'],

        'RMSE treino': metricas_train['RMSE'],
        'RMSE teste': metricas_test['RMSE'],

        'R2 treino': metricas_train['R2'],
        'R2 teste': metricas_test['R2']
    })

In [ ]:
# o trade-off entre viés e variância
df_profundidade = pd.DataFrame(resultados_profundidade)

df_profundidade

,max_depth,MAE treino,MAE teste,RMSE treino,RMSE teste,R2 treino,R2 teste
0,2,52.590749,65.640738,163.487234,307.807614,0.526505,-0.954115
1,3,56.364983,71.967801,133.188628,317.571728,0.685745,-1.080057
2,5,35.638830,52.029897,87.088817,289.849862,0.865639,-0.732757
3,7,22.940175,40.370094,55.892123,285.655751,0.944659,-0.682974
4,10,13.972520,35.926058,32.009010,285.275899,0.981849,-0.678501
5,15,5.015065,33.857614,12.877652,285.515430,0.997062,-0.681321
6,20,1.451083,34.609411,5.690429,288.465886,0.999426,-0.716249

* Cross-Validation

In [76]:
# Importação de bibliotecas cross validation
from sklearn.model_selection import cross_validate

modelo_dt_cv = DecisionTreeRegressor(
    max_depth=10,
    random_state=42
)

pipeline_dt_cv = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_dt_cv)
    ]
)


# Validação cruzada com 5 folds, utilizando as métricas MAE, RMSE e R², retornando também o score de treino 

cv_resultados = cross_validate(
    pipeline_dt_cv,
    X_train,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True
)

(7995, 8)

In [85]:
# Resultados da validação cruzada
# cv_resultados.keys()
# cv_resultados.items()

cv_df = pd.DataFrame({
    'Fold': range(1, 6),

    'MAE treino':
        -cv_resultados['train_neg_mean_absolute_error'],

    'MAE validação':
        -cv_resultados['test_neg_mean_absolute_error'],

    'RMSE treino':
        -cv_resultados['train_neg_root_mean_squared_error'],

    'RMSE validação':
        -cv_resultados['test_neg_root_mean_squared_error'],

    'R2 treino':
        cv_resultados['train_r2'],

    'R2 validação':
        cv_resultados['test_r2']
})

cv_df

,Fold,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação
0,1,13.360797,28.716191,30.608962,174.772580,0.979558,0.690574
1,2,13.718210,25.140158,30.287959,171.127096,0.984705,0.307267
2,3,13.319781,25.996841,29.234613,130.013412,0.983482,0.775440
3,4,13.316284,23.052769,29.152690,87.494804,0.986411,0.761274
4,5,18.129309,26.491915,39.855824,87.143652,0.974434,0.774443

In [95]:
print("cv_df mean".upper())
print(cv_df.mean(numeric_only=True))
print("___________________________________________________________")
print("cv_df std".upper())
print(cv_df.std(numeric_only=True))

CV_DF MEAN
Fold                3.000000
MAE treino         14.368876
MAE validação      25.879575
RMSE treino        31.828010
RMSE validação    130.110309
R2 treino           0.981718
R2 validação        0.661800
dtype: float64
___________________________________________________________
CV_DF STD
Fold               1.581139
MAE treino         2.108850
MAE validação      2.059895
RMSE treino        4.532844
RMSE validação    42.834914
R2 treino          0.004790
R2 validação       0.201258
dtype: float64

In [99]:
# Na base de teste.
profundidades = [2, 3, 5, 7, 10, 15, 20]
resultados_cv_depth = []
for profundidade in profundidades:

    modelo = DecisionTreeRegressor(
        max_depth=profundidade,
        random_state=42
    )

    pipeline = Pipeline(
        steps=[
            ('preprocessor', preprocessor),
            ('modelo', modelo)
        ]
    )

    cv = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=5,
        scoring=[
            'neg_mean_absolute_error',
            'neg_root_mean_squared_error',
            'r2'
        ],
        return_train_score=True
    )

    resultados_cv_depth.append({
        'max_depth': profundidade,

        'MAE treino':
            -cv['train_neg_mean_absolute_error'].mean(),

        'MAE validação':
            -cv['test_neg_mean_absolute_error'].mean(),

        'RMSE treino':
            -cv['train_neg_root_mean_squared_error'].mean(),

        'RMSE validação':
            -cv['test_neg_root_mean_squared_error'].mean(),

        'R2 treino':
            cv['train_r2'].mean(),

        'R2 validação':
            cv['test_r2'].mean(),

        'R2 validação std':
            cv['test_r2'].std()
    })

In [100]:
df_cv_depth = pd.DataFrame(resultados_cv_depth)

df_cv_depth

,max_depth,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação,R2 validação std
0,2,52.649722,54.500200,162.559645,176.684186,0.523029,0.335993,0.305824
1,3,55.274917,59.045371,133.737074,169.805431,0.679307,0.422373,0.149475
2,5,38.879173,42.824155,92.917080,138.766547,0.844241,0.584405,0.206332
3,7,24.988390,32.304489,59.049831,131.638950,0.936942,0.664059,0.133424
4,10,14.368876,25.879575,31.828010,130.110309,0.981718,0.661800,0.180011
5,15,5.236175,23.799544,13.667088,126.672710,0.996625,0.666022,0.222603
6,20,1.447648,22.873856,5.373775,108.381546,0.999483,0.734643,0.218466

In [102]:
print(f"cv['R2 validação'].std(): {cv_df['R2 validação'].std()}")
print("____________________________________________________________")
print(f"cv['test_r2'].std(): {cv['test_r2'].std()}".upper())

cv['R2 validação'].std(): 0.2012582598349565
____________________________________________________________
CV['TEST_R2'].STD(): 0.2184656979934817

In [103]:
df_cv_depth

,max_depth,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação,R2 validação std
0,2,52.649722,54.500200,162.559645,176.684186,0.523029,0.335993,0.305824
1,3,55.274917,59.045371,133.737074,169.805431,0.679307,0.422373,0.149475
2,5,38.879173,42.824155,92.917080,138.766547,0.844241,0.584405,0.206332
3,7,24.988390,32.304489,59.049831,131.638950,0.936942,0.664059,0.133424
4,10,14.368876,25.879575,31.828010,130.110309,0.981718,0.661800,0.180011
5,15,5.236175,23.799544,13.667088,126.672710,0.996625,0.666022,0.222603
6,20,1.447648,22.873856,5.373775,108.381546,0.999483,0.734643,0.218466