In [1]:
import pandas as pd
import numpy as np
import seaborn as srn
import matplotlib.pyplot as plt

In [2]:
from charset_normalizer import from_path
caminho = "../data/raw/Superstore.csv"
resultado = from_path(caminho).best()
encoding_detectado = resultado.encoding
confianca = resultado.coherence
print(encoding_detectado)
print(confianca)

cp1250
0.7082

In [3]:
df = pd.read_csv("../data/raw/Superstore.csv", encoding= 'cp1250')

In [4]:
df.shape

(9994, 21)

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [7]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

# Objetivo Prever o lucro esperado de uma transação a partir das características comerciais conhecidas da venda.

In [8]:
df["Country"].value_counts()

Country
United States    9994
Name: count, dtype: int64

In [9]:
df.nunique() #valores únicos de todas as colunas

Row ID           9994
Order ID         5009
Order Date       1238
Ship Date        1334
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              531
State              49
Postal Code       631
Region              4
Product ID       1862
Category            3
Sub-Category       17
Product Name     1841
Sales            5825
Quantity           14
Discount           12
Profit           7287
dtype: int64

In [10]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [11]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].corr()

             Sales  Quantity  Discount    Profit
Sales     1.000000  0.200795 -0.028190  0.479064
Quantity  0.200795  1.000000  0.008623  0.066253
Discount -0.028190  0.008623  1.000000 -0.219487
Profit    0.479064  0.066253 -0.219487  1.000000

In [12]:
features = [
    "Ship Mode",
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Sales',
    'Quantity',
    'Discount'
    ] 

target =  'Profit'

In [13]:
X = df[features] # variáveis independentes/preditoras
y = df[target] #variável dependente/alvo

In [14]:
X.shape
y.shape

(9994,)

#### Separação de features por tipo

In [15]:
features_numericas = [
    'Sales',
    'Quantity',
    'Discount'
]

features_categoricas = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

In [16]:
print(X.head())
print(X.shape)
print(y.head()) 
print(y.shape) 
print(X.dtypes)

        Ship Mode    Segment Region         Category Sub-Category     Sales  \
0    Second Class   Consumer  South        Furniture    Bookcases  261.9600
1    Second Class   Consumer  South        Furniture       Chairs  731.9400
2    Second Class  Corporate   West  Office Supplies       Labels   14.6200
3  Standard Class   Consumer  South        Furniture       Tables  957.5775
4  Standard Class   Consumer  South  Office Supplies      Storage   22.3680

   Quantity  Discount
0         2      0.00
1         3      0.00
2         2      0.00
3         5      0.45
4         2      0.20
(9994, 8)
0     41.9136
1    219.5820
2      6.8714
3   -383.0310
4      2.5164
Name: Profit, dtype: float64
(9994,)
Ship Mode        object
Segment          object
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
dtype: object

#### Importação de bibliotecas scikit-learn > train_test_split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
# 
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [19]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (7995, 8)
X_test: (1999, 8)
y_train: (7995,)
y_test: (1999,)

In [20]:
X_train['Segment'].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

#### Criação do One_hot_encoder

In [21]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

features_numericas = [
    'Sales',
    'Quantity',
    'Discount'
]

features_categoricas = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

encoder = OneHotEncoder(
    handle_unknown='ignore'
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            encoder,
            features_categoricas
        )
    ],
    remainder='passthrough'
)

In [22]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Ship Mode', 'Segment', 'Region', 'Category',
                                  'Sub-Category'])])

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

modelo_lr = LinearRegression()

pipeline_lr = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_lr)
    ]
)

pipeline_lr.fit(X_train, y_train)

y_pred_lr = pipeline_lr.predict(X_test)

In [24]:
print(y_pred_lr[:10])

[  79.03485168   36.24686834   55.75657936  -51.62315952 -153.79443364
    1.41577812  -14.23549171   95.41024949  -80.36007     -69.61534622]

In [25]:
comparacao = pd.DataFrame({
    'Profit Real': y_test.values,
    'Profit Previsto': y_pred_lr
})

comparacao.head(10)

   Profit Real  Profit Previsto
0      21.1428        79.034852
1      11.4600        36.246868
2      17.1580        55.756579
3     -15.1470       -51.623160
4      -6.4233      -153.794434
5       8.6744         1.415778
6     -73.7061       -14.235492
7       8.6900        95.410249
8     -15.0800       -80.360070
9      17.9080       -69.615346

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [27]:
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"MAE:  {mae_lr:.2f}")
print(f"RMSE: {rmse_lr:.2f}")
print(f"R²:   {r2_lr:.4f}")

print()
print(f"Média Profit teste:   {y_test.mean():.2f}")
print(f"Mediana Profit teste: {y_test.median():.2f}")
print(f"Desvio padrão:        {y_test.std():.2f}")

MAE:  67.76
RMSE: 282.51
R²:   -0.6461

Média Profit teste:   20.50
Mediana Profit teste: 8.69
Desvio padrão:        220.25

In [28]:
from visualizacao.resultado import calcular_metricas_regressao
from modelagem.metricas import registrar_resultado

In [29]:
resultados = pd.DataFrame()

In [30]:
resultados = pd.DataFrame()

metricas_Lr = calcular_metricas_regressao(y_test, y_pred_lr)

In [31]:
resultados = registrar_resultado(resultados, 'Regressão Linear', metricas_Lr)

In [32]:
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.495678,8.69,220.248479

#### Arvore de decisão

In [33]:
# Importação da biblioteca DecisionTreeRegressor do scikit-learn
from sklearn.tree import DecisionTreeRegressor

In [34]:
# modelo sem poda explicita, avaliação de overfitting, sem regularização, sem poda, sem limite de profundidade, sem limite de folhas, sem limite de amostras mínimas por folha
modelo_dt = DecisionTreeRegressor(random_state=42)

#Criação do pipeline para o modelo de árvore de decisão
pipeline_dt = Pipeline(
    steps=[
        ('processor', preprocessor),
        ('modelo', modelo_dt)
    ]
)

In [35]:
# Treinamento do modelo de árvore de decisão
pipeline_dt.fit(X_train, y_train)

Pipeline(steps=[('processor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo', DecisionTreeRegressor(random_state=42))])

In [36]:
# Previsão dos valores de Profit para o conjunto de teste usando o modelo de árvore de decisão
y_pred_dt_train = pipeline_dt.predict(X_train)
y_pred_dt = pipeline_dt.predict(X_test)
# Métricas
metricas_dt_train = calcular_metricas_regressao(
    y_train,
    y_pred_dt_train
)
resultados = registrar_resultado(
    resultados,
    "Decision Tree _ train",
    metricas_dt_train
)
metricas_dt = calcular_metricas_regressao(
    y_test,
    y_pred_dt
)
resultados = registrar_resultado(
    resultados,
    "Decision Tree test",
    metricas_dt
)
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.495678,8.690,220.248479
1,Decision Tree _ train,0.055392,0.911667,0.954812,0.999984,30.697456,8.636,237.603758
2,Decision Tree test,34.614556,81762.376829,285.941212,-0.686339,20.495678,8.690,220.248479

In [37]:
# Modelo com profundidade máxima dentro de uma variavel com um for, sem limite de folhas, sem limite de amostras mínimas por folha
profundidades = [2, 3, 5, 7, 10, 15, 20]
resultados_profundidade = []

for profundidade in profundidades:

    modelo = DecisionTreeRegressor(
        max_depth=profundidade,
        random_state=42
    )

    pipeline = Pipeline(
        steps=[
            ('preprocessor', preprocessor),
            ('modelo', modelo)
        ]
    )

    pipeline.fit(X_train, y_train)

    pred_train = pipeline.predict(X_train)
    pred_test = pipeline.predict(X_test)

    metricas_train = calcular_metricas_regressao(
        y_train,
        pred_train
    )

    metricas_test = calcular_metricas_regressao(
        y_test,
        pred_test
    )

    resultados_profundidade.append({
        'max_depth': profundidade,

        'MAE treino': metricas_train['MAE'],
        'MAE teste': metricas_test['MAE'],

        'RMSE treino': metricas_train['RMSE'],
        'RMSE teste': metricas_test['RMSE'],

        'R2 treino': metricas_train['R2'],
        'R2 teste': metricas_test['R2']
    })

In [38]:
# o trade-off entre viés e variância
df_profundidade = pd.DataFrame(resultados_profundidade)

df_profundidade

,max_depth,MAE treino,MAE teste,RMSE treino,RMSE teste,R2 treino,R2 teste
0,2,52.590749,65.640738,163.487234,307.807614,0.526505,-0.954115
1,3,56.364983,71.967801,133.188628,317.571728,0.685745,-1.080057
2,5,35.638830,52.029897,87.088817,289.849862,0.865639,-0.732757
3,7,22.940175,40.370094,55.892123,285.655751,0.944659,-0.682974
4,10,13.972520,35.926058,32.009010,285.275899,0.981849,-0.678501
5,15,5.015065,33.857614,12.877652,285.515430,0.997062,-0.681321
6,20,1.451083,34.609411,5.690429,288.465886,0.999426,-0.716249

* Cross-Validation

In [39]:
# Importação de bibliotecas cross validation
from sklearn.model_selection import cross_validate

modelo_dt_cv = DecisionTreeRegressor(
    max_depth=10,
    random_state=42
)

pipeline_dt_cv = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_dt_cv)
    ]
)


# Validação cruzada com 5 folds, utilizando as métricas MAE, RMSE e R², retornando também o score de treino 

cv_resultados = cross_validate(
    pipeline_dt_cv,
    X_train,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True
)

In [40]:
# Resultados da validação cruzada
# cv_resultados.keys()
# cv_resultados.items()

cv_df = pd.DataFrame({
    'Fold': range(1, 6),

    'MAE treino':
        -cv_resultados['train_neg_mean_absolute_error'],

    'MAE validação':
        -cv_resultados['test_neg_mean_absolute_error'],

    'RMSE treino':
        -cv_resultados['train_neg_root_mean_squared_error'],

    'RMSE validação':
        -cv_resultados['test_neg_root_mean_squared_error'],

    'R2 treino':
        cv_resultados['train_r2'],

    'R2 validação':
        cv_resultados['test_r2']
})

cv_df

,Fold,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação
0,1,13.360797,28.716191,30.608962,174.772580,0.979558,0.690574
1,2,13.718210,25.140158,30.287959,171.127096,0.984705,0.307267
2,3,13.319781,25.996841,29.234613,130.013412,0.983482,0.775440
3,4,13.316284,23.052769,29.152690,87.494804,0.986411,0.761274
4,5,18.129309,26.491915,39.855824,87.143652,0.974434,0.774443

In [41]:
print("cv_df mean".upper())
print(cv_df.mean(numeric_only=True))
print("___________________________________________________________")
print("cv_df std".upper())
print(cv_df.std(numeric_only=True))

CV_DF MEAN
Fold                3.000000
MAE treino         14.368876
MAE validação      25.879575
RMSE treino        31.828010
RMSE validação    130.110309
R2 treino           0.981718
R2 validação        0.661800
dtype: float64
___________________________________________________________
CV_DF STD
Fold               1.581139
MAE treino         2.108850
MAE validação      2.059895
RMSE treino        4.532844
RMSE validação    42.834914
R2 treino          0.004790
R2 validação       0.201258
dtype: float64

In [42]:
# Na base de teste.
profundidades = [2, 3, 5, 7, 10, 15, 20]
resultados_cv_depth = []
for profundidade in profundidades:

    modelo = DecisionTreeRegressor(
        max_depth=profundidade,
        random_state=42
    )

    pipeline = Pipeline(
        steps=[
            ('preprocessor', preprocessor),
            ('modelo', modelo)
        ]
    )

    cv = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=5,
        scoring=[
            'neg_mean_absolute_error',
            'neg_root_mean_squared_error',
            'r2'
        ],
        return_train_score=True
    )

    resultados_cv_depth.append({
        'max_depth': profundidade,

        'MAE treino':
            -cv['train_neg_mean_absolute_error'].mean(),

        'MAE validação':
            -cv['test_neg_mean_absolute_error'].mean(),

        'RMSE treino':
            -cv['train_neg_root_mean_squared_error'].mean(),

        'RMSE validação':
            -cv['test_neg_root_mean_squared_error'].mean(),

        'R2 treino':
            cv['train_r2'].mean(),

        'R2 validação':
            cv['test_r2'].mean(),

        'R2 validação std':
            cv['test_r2'].std()
    })

In [43]:
df_cv_depth = pd.DataFrame(resultados_cv_depth)

df_cv_depth

,max_depth,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação,R2 validação std
0,2,52.649722,54.500200,162.559645,176.684186,0.523029,0.335993,0.305824
1,3,55.274917,59.045371,133.737074,169.805431,0.679307,0.422373,0.149475
2,5,38.879173,42.824155,92.917080,138.766547,0.844241,0.584405,0.206332
3,7,24.988390,32.304489,59.049831,131.638950,0.936942,0.664059,0.133424
4,10,14.368876,25.879575,31.828010,130.110309,0.981718,0.661800,0.180011
5,15,5.236175,23.799544,13.667088,126.672710,0.996625,0.666022,0.222603
6,20,1.447648,22.873856,5.373775,108.381546,0.999483,0.734643,0.218466

In [44]:
print(f"cv['R2 validação'].std(): {cv_df['R2 validação'].std()}")
print("____________________________________________________________")
print(f"cv['test_r2'].std(): {cv['test_r2'].std()}".upper())

cv['R2 validação'].std(): 0.2012582598349565
____________________________________________________________
CV['TEST_R2'].STD(): 0.2184656979934817

In [45]:
df_cv_depth

,max_depth,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação,R2 validação std
0,2,52.649722,54.500200,162.559645,176.684186,0.523029,0.335993,0.305824
1,3,55.274917,59.045371,133.737074,169.805431,0.679307,0.422373,0.149475
2,5,38.879173,42.824155,92.917080,138.766547,0.844241,0.584405,0.206332
3,7,24.988390,32.304489,59.049831,131.638950,0.936942,0.664059,0.133424
4,10,14.368876,25.879575,31.828010,130.110309,0.981718,0.661800,0.180011
5,15,5.236175,23.799544,13.667088,126.672710,0.996625,0.666022,0.222603
6,20,1.447648,22.873856,5.373775,108.381546,0.999483,0.734643,0.218466

* GridSearchCV

In [46]:
# Importação da biblioteca GridSearchCV do scikit-learn
from sklearn.model_selection import GridSearchCV

In [47]:
# Definição do modelo de árvore de decisão

modelo_dt_grid = DecisionTreeRegressor(
    random_state=42
)

pipeline_dt_grid = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_dt_grid)
    ]
)

# Definição dos hiperparâmetros a serem testados no GridSearchCV
param_grid = {
    'modelo__max_depth': [5, 10, 15, 20, None],
    'modelo__min_samples_split': [2, 5, 10],
    'modelo__min_samples_leaf': [1, 2, 5, 10]
}

In [48]:
# Criando o objeto GridSearchCV
grid_dt = GridSearchCV(
    estimator=pipeline_dt_grid,
    param_grid=param_grid,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1,
    return_train_score=True
)

# Estimador
estimator=pipeline_dt_grid

# param_grid
param_grid=param_grid

# Scoring
scoring='neg_root_mean_squared_error'

In [49]:
# Treinando o modelo com GridSearchCV
grid_dt.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Ship '
                                                                          'Mode',
                                                                          'Segment',
                                                                          'Region',
                                                                          'Category',
                                                                          'Sub-Category'])])),
                                       ('modelo',
                                        DecisionTreeRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'modelo__max_depth': [5, 10, 15, 20, None],
                         'modelo__min_samples_leaf': [1, 2, 5, 10],
                         'modelo__min_samples_split': [2, 5, 10]},
             return_train_score=True, scoring='neg_root_mean_squared_error')

In [50]:
# Comparando combinações de hiperparâmetros
print(grid_dt.best_params_)
print("____________________________________________________________")
print(-grid_dt.best_score_)
print("____________________________________________________________")
melhor_dt = grid_dt.best_estimator_
print(melhor_dt)
# print("____________________________________________________________")
# print(melhor_dt.predict(X_test))

{'modelo__max_depth': 20, 'modelo__min_samples_leaf': 1, 'modelo__min_samples_split': 2}
____________________________________________________________
108.38154555023539
____________________________________________________________
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo',
                 DecisionTreeRegressor(max_depth=20, random_state=42))])

In [51]:
# Refinamento do modelo de árvore de decisão com os melhores hiperparâmetros encontrados pelo GridSearchCV
param_grid_refinado = {
    'modelo__max_depth': [15, 20, 25, 30, None],
    'modelo__min_samples_split': [2, 3, 5],
    'modelo__min_samples_leaf': [1, 2, 3]
}

grid_dt_refinado = GridSearchCV(
    estimator=pipeline_dt_grid,
    param_grid=param_grid_refinado,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1,
    return_train_score=True
)

In [52]:
# Treinando o modelo refinado com GridSearchCV
grid_dt_refinado.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Ship '
                                                                          'Mode',
                                                                          'Segment',
                                                                          'Region',
                                                                          'Category',
                                                                          'Sub-Category'])])),
                                       ('modelo',
                                        DecisionTreeRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'modelo__max_depth': [15, 20, 25, 30, None],
                         'modelo__min_samples_leaf': [1, 2, 3],
                         'modelo__min_samples_split': [2, 3, 5]},
             return_train_score=True, scoring='neg_root_mean_squared_error')

In [53]:
# Obtenção dos melhores hiperparâmetros do modelo refinado
print(grid_dt_refinado.best_params_)
print("____________________________________________________________")
print(-grid_dt_refinado.best_score_)

{'modelo__max_depth': 20, 'modelo__min_samples_leaf': 1, 'modelo__min_samples_split': 2}
____________________________________________________________
108.38154555023539

In [54]:
# Recuperando o melhor modelo refinado
melhor_dt = grid_dt_refinado.best_estimator_

# Validando o modelo refinado na base de teste
y_pred_dt_final = melhor_dt.predict(X_test)

# Métricas do modelo refinado
metricas_dt_final = calcular_metricas_regressao(
    y_test,
    y_pred_dt_final
)

metricas_dt_final

{'MAE': 34.60941104291444,
 'MSE': 83212.56723903443,
 'RMSE': np.float64(288.46588574567085),
 'R2': -0.7162493842972399,
 'Média': np.float64(20.495677788894444),
 'Mediana': np.float64(8.69),
 'Desvio Padrão': np.float64(220.24847920729428)}

In [55]:
# Registrando os resultados do modelo refinado
resultados = registrar_resultado(
    resultados,
    'Decision Tree Otimizada',
    metricas_dt_final
)
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.495678,8.690,220.248479
1,Decision Tree _ train,0.055392,0.911667,0.954812,0.999984,30.697456,8.636,237.603758
2,Decision Tree test,34.614556,81762.376829,285.941212,-0.686339,20.495678,8.690,220.248479
3,Decision Tree Otimizada,34.609411,83212.567239,288.465886,-0.716249,20.495678,8.690,220.248479

##### Analise de Residuos e erros!

In [56]:
analise_erros_dt = pd.DataFrame({
    'Profit_real': y_test,
    'Profit_previsto': y_pred_dt_final
})
analise_erros_dt['Erro'] = (
    analise_erros_dt['Profit_real']
    - analise_erros_dt['Profit_previsto']
)
analise_erros_dt['Erro_absoluto'] = (
    analise_erros_dt['Erro'].abs()
)

maiores_erros_dt = (
    analise_erros_dt
    .sort_values(
        'Erro_absoluto',
        ascending=False
    )
    .head(20)
)
Erro = maiores_erros_dt['Profit_real'] - maiores_erros_dt['Profit_previsto']
print("Erros")
Erro
print("Maiores erros do modelo Decision Tree Otimizada:")
maiores_erros_dt

Erros
Maiores erros do modelo Decision Tree Otimizada:

      Profit_real  Profit_previsto        Erro  Erro_absoluto
2697   -1811.0784        8399.9760 -10211.0544     10211.0544
1803   -1049.3406        2504.2216  -3553.5622      3553.5622
683    -3839.9904        -509.9970  -3329.9934      3329.9934
3011   -3399.9800       -6599.9780   3199.9980      3199.9980
3151   -2639.9912         239.9960  -2879.9872      2879.9872
4277    2365.9818        4630.4755  -2264.4937      2264.4937
2492    1228.1787        2591.9568  -1363.7781      1363.7781
6014     363.9048        1453.1238  -1089.2190      1089.2190
353     1415.4296         327.5922   1087.8374      1087.8374
1438    -350.4900       -1359.9920   1009.5020      1009.5020
5198    -786.0144          83.2810   -869.2954       869.2954
251      636.0003        1416.8000   -780.7997       780.7997
8100     377.7300        1143.8910   -766.1610       766.1610
7243    -630.8820       -1359.9920    729.1100       729.1100
4128    -944.9946       -1665.0522    720.0576       720.0576
994     1276.4871         626.1850    650.3021       650.3021
509     3177.4750        2591.9568    585.5182       585.5182
7583     909.9818        1459.2000   -549.2182       549.2182
9639   -1862.3124       -1359.9920   -502.3204       502.3204
2358    -553.6476         -69.8900   -483.7576       483.7576

In [57]:
colunas_analise = [
    'Category',
    'Sub-Category',
    'Sales',
    'Quantity',
    'Discount',
    'Profit'
]

casos_extremos_dt = df.loc[
    maiores_erros_dt.index,
    colunas_analise
].copy()

In [58]:
casos_extremos_dt['Profit_previsto'] = (
    maiores_erros_dt['Profit_previsto']
)

casos_extremos_dt['Erro_absoluto'] = (
    maiores_erros_dt['Erro_absoluto']
)

In [59]:
casos_extremos_dt = casos_extremos_dt.sort_values(
    'Erro_absoluto',
    ascending=False
)

casos_extremos_dt

,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit_previsto,Erro_absoluto
2697,Technology,Machines,22638.480,6,0.5,-1811.0784,8399.9760,10211.0544
1803,Office Supplies,Supplies,4663.736,7,0.2,-1049.3406,2504.2216,3553.5622
683,Technology,Machines,7999.980,4,0.5,-3839.9904,-509.9970,3329.9934
3011,Technology,Machines,2549.985,5,0.7,-3399.9800,-6599.9780,3199.9980
3151,Technology,Machines,1799.994,2,0.7,-2639.9912,239.9960,2879.9872
4277,Technology,Machines,9099.930,7,0.0,2365.9818,4630.4755,2264.4937
2492,Technology,Phones,4548.810,7,0.0,1228.1787,2591.9568,1363.7781
6014,Technology,Phones,4158.912,8,0.2,363.9048,1453.1238,1089.2190
353,Office Supplies,Binders,4355.168,4,0.2,1415.4296,327.5922,1087.8374
1438,Furniture,Chairs,2453.430,5,0.3,-350.4900,-1359.9920,1009.5020
5198,Office Supplies,Supplies,3930.072,3,0.2,-786.0144,83.2810,869.2954
251,Technology,Accessories,3347.370,13,0.0,636.0003,1416.8000,780.7997
8100,Technology,Machines,3357.600,3,0.2,377.7300,1143.8910,766.1610
7243,Furniture,Chairs,4416.174,9,0.3,-630.8820,-1359.9920,729.1100
4128,Technology,Machines,2624.985,3,0.5,-944.9946,-1665.0522,720.0576
994,Office Supplies,Binders,2715.930,7,0.0,1276.4871,626.1850,650.3021
509,Office Supplies,Binders,6354.950,5,0.0,3177.4750,2591.9568,585.5182
7583,Technology,Phones,3499.930,7,0.0,909.9818,1459.2000,549.2182
9639,Furniture,Tables,4297.644,13,0.4,-1862.3124,-1359.9920,502.3204
2358,Furniture,Tables,1071.576,4,0.4,-553.6476,-69.8900,483.7576

#### Experimento de diagnostico das variações do erro quadratico RMSE

In [60]:
analise_erros_dt['Erro_quadrado'] = (
    analise_erros_dt['Erro'] ** 2
)
erro_quadrado_total = (
    analise_erros_dt['Erro_quadrado'].sum()
)
top20_erro_quadrado = (
    analise_erros_dt
    .nlargest(20, 'Erro_absoluto')['Erro_quadrado']
    .sum()
)
percentual_top20 = (
    top20_erro_quadrado
    / erro_quadrado_total
) * 100

percentual_top20

np.float64(97.05877554914329)

##### Modelo com Random Forest

In [61]:
# Importação da biblioteca RandomForestRegressor do scikit-learn
from sklearn.ensemble import RandomForestRegressor

In [62]:
modelo_rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)
pipeline_rf = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_rf)
    ]       
)

In [63]:
# Cross-validation para o modelo Random Forest
cv_rf = cross_validate(
    pipeline_rf,
    X_train,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True,
    n_jobs=-1
)

In [64]:
# Transformando os resultados da validação cruzada em um DataFrame
resultado_rf_cv = pd.DataFrame({
    'Fold': range(1, 6),

    'MAE treino':
        -cv_rf['train_neg_mean_absolute_error'],

    'MAE validação':
        -cv_rf['test_neg_mean_absolute_error'],

    'RMSE treino':
        -cv_rf['train_neg_root_mean_squared_error'],

    'RMSE validação':
        -cv_rf['test_neg_root_mean_squared_error'],

    'R2 treino':
        cv_rf['train_r2'],

    'R2 validação':
        cv_rf['test_r2']
})

resultado_rf_cv

,Fold,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação
0,1,7.543403,19.827868,50.261266,99.399909,0.944882,0.899912
1,2,7.080873,21.297156,35.130337,179.419790,0.979423,0.238501
2,3,7.232658,22.109878,42.375497,143.387621,0.965295,0.726864
3,4,7.652364,17.583253,45.182539,74.650717,0.967359,0.826219
4,5,8.195245,17.008703,54.269317,62.983515,0.952600,0.882175

In [65]:
# Calculo das medias e desvios padrão da validação cruzada
print("***********Medias**************")
print(resultado_rf_cv.drop(columns='Fold').mean())
print("***********Desvio Padrão**************")
print(resultado_rf_cv.drop(columns='Fold').std())

***********Medias**************
MAE treino          7.540908
MAE validação      19.565372
RMSE treino        45.443791
RMSE validação    111.968311
R2 treino           0.961912
R2 validação        0.714734
dtype: float64
***********Desvio Padrão**************
MAE treino         0.432214
MAE validação      2.236506
RMSE treino        7.364577
RMSE validação    48.700495
R2 treino          0.013458
R2 validação       0.274636
dtype: float64

* Otimização do Random Forest

In [66]:
param_grid_rf = {
    'modelo__n_estimators': [100, 200],
    'modelo__max_depth': [10, 20, None],
    'modelo__min_samples_split': [2, 5],
    'modelo__min_samples_leaf': [1, 2, 5]
}

In [67]:
# Definição do grid search para o modelo Random Forest

grid_rf = GridSearchCV(
    estimator=pipeline_rf,
    param_grid=param_grid_rf,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1,
    return_train_score=True
)

# Treinando o modelo Random Forest com GridSearchCV
grid_rf.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Ship '
                                                                          'Mode',
                                                                          'Segment',
                                                                          'Region',
                                                                          'Category',
                                                                          'Sub-Category'])])),
                                       ('modelo',
                                        RandomForestRegressor(n_jobs=-1,
                                                              random_state=42))]),
             n_jobs=-1,
             param_grid={'modelo__max_depth': [10, 20, None],
                         'modelo__min_samples_leaf': [1, 2, 5],
                         'modelo__min_samples_split': [2, 5],
                         'modelo__n_estimators': [100, 200]},
             return_train_score=True, scoring='neg_root_mean_squared_error')

In [68]:
# Obtenção dos melhores hiperparâmetros do modelo Random Forest
print("Melhores hiperparâmetros:")
print(grid_rf.best_params_)
print("Melhor estimador:")
print(grid_rf.best_estimator_)
print("Melhor pontuação:")
print(-grid_rf.best_score_)

Melhores hiperparâmetros:
{'modelo__max_depth': None, 'modelo__min_samples_leaf': 1, 'modelo__min_samples_split': 2, 'modelo__n_estimators': 200}
Melhor estimador:
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])
Melhor pontuação:
110.65473357221504

In [69]:
# Otimização do modelo Random Forest com os melhores hiperparâmetros encontrados pelo GridSearchCV
melhor_rf = grid_rf.best_estimator_

# Cross-validation para o modelo Random Forest otimizado
cv_melhor_rf = cross_validate(
    melhor_rf,
    X_train,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True,
    n_jobs=-1
)

# Transformando os resultados da validação cruzada do modelo Random Forest otimizado em um DataFrame
metricas_cv_melhor_rf = pd.DataFrame({
    'MAE treino':
        -cv_melhor_rf['train_neg_mean_absolute_error'],

    'MAE validação':
        -cv_melhor_rf['test_neg_mean_absolute_error'],

    'RMSE treino':
        -cv_melhor_rf['train_neg_root_mean_squared_error'],

    'RMSE validação':
        -cv_melhor_rf['test_neg_root_mean_squared_error'],

    'R2 treino':
        cv_melhor_rf['train_r2'],

    'R2 validação':
        cv_melhor_rf['test_r2']
})

In [70]:
# Calculo das medias e desvios padrão da validação cruzada do modelo Random Forest otimizado
print("***********Medias**************")    
print(metricas_cv_melhor_rf.mean())
print("***********Desvios Padrão**************")    
print(metricas_cv_melhor_rf.std())
print("***********RMSE validação média**************")
print(metricas_cv_melhor_rf['RMSE validação'].mean())

***********Medias**************
MAE treino          7.486122
MAE validação      19.470317
RMSE treino        46.268195
RMSE validação    110.654734
R2 treino           0.960514
R2 validação        0.719095
dtype: float64
***********Desvios Padrão**************
MAE treino         0.364873
MAE validação      2.226043
RMSE treino        6.952427
RMSE validação    49.002183
R2 treino          0.013770
R2 validação       0.274215
dtype: float64
***********RMSE validação média**************
110.65473357221504

In [115]:
# Avaliação do modelo Random Forest otimizado na base de teste
melhor_rf = grid_rf.best_estimator_

y_pred_rf_final = melhor_rf.predict(X_test)

# Métricas do modelo Random Forest otimizado
metricas_rf_final = calcular_metricas_regressao(
    y_test,
    y_pred_rf_final
)

# metricas_rf_final

# Registrando os resultados do modelo Random Forest otimizado
resultados = registrar_resultado(
    resultados,
    'Random Forest Otimizado',
    metricas_rf_final
)
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.495678,8.690,220.248479
1,Decision Tree _ train,0.055392,0.911667,0.954812,0.999984,30.697456,8.636,237.603758
2,Decision Tree test,34.614556,81762.376829,285.941212,-0.686339,20.495678,8.690,220.248479
3,Decision Tree Otimizada,34.609411,83212.567239,288.465886,-0.716249,20.495678,8.690,220.248479
4,Random Forest Otimizado,25.804526,50350.478877,224.389124,-0.038473,20.495678,8.690,220.248479

In [ ]:
# Limpeza do DataFrame de resultados, removendo duplicatas com base na coluna 'Modelo' e mantendo a última ocorrência, e resetando o índice.
resultados = resultados.drop_duplicates(subset=['Modelo'], keep="last").reset_index(drop=True)

In [117]:
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.495678,8.69,220.248479
1,Decision Tree test,34.614556,81762.376829,285.941212,-0.686339,20.495678,8.69,220.248479
2,Decision Tree Otimizada,34.609411,83212.567239,288.465886,-0.716249,20.495678,8.69,220.248479
3,Random Forest Otimizado,25.804526,50350.478877,224.389124,-0.038473,20.495678,8.69,220.248479

In [116]:
# Exclusão do modelo "Random Forest Otimizado" dos resultados
excluir = resultados.loc[resultados["Modelo"] == "Decision Tree _ train"]
resultados = resultados.drop(excluir.index).reset_index(drop=True)

In [118]:
# Analise dos erros do modelo Random Forest otimizado
analise_erros_rf = pd.DataFrame({
    'Profit_real': y_test,
    'Profit_previsto': y_pred_rf_final
})

analise_erros_rf['Erro'] = (
    analise_erros_rf['Profit_real']
    - analise_erros_rf['Profit_previsto']
)

analise_erros_rf['Erro_absoluto'] = (
    analise_erros_rf['Erro'].abs()
)

# Maiores 20 erros do modelo Random Forest otimizado
maiores_erros_rf = (
    analise_erros_rf
    .sort_values(
        'Erro_absoluto',
        ascending=False
    )
    .head(20)
)

maiores_erros_rf

      Profit_real  Profit_previsto         Erro  Erro_absoluto
2697   -1811.0784      6484.089493 -8295.167893    8295.167893
683    -3839.9904      -173.716955 -3666.273445    3666.273445
1803   -1049.3406       993.137338 -2042.477938    2042.477938
3151   -2639.9912     -1085.635201 -1554.355999    1554.355999
5198    -786.0144       548.339231 -1334.353631    1334.353631
9165     503.6400      -769.471148  1273.111148    1273.111148
9639   -1862.3124      -787.253871 -1075.058529    1075.058529
4277    2365.9818      3419.272023 -1053.290223    1053.290223
509     3177.4750      2198.482701   978.992299     978.992299
5884     196.5036      1059.057286  -862.553686     862.553686
318     1995.9900      1223.135306   772.854694     772.854694
1199   -1850.9464     -1256.106523  -594.839877     594.839877
3011   -3399.9800     -2805.159698  -594.820302     594.820302
8100     377.7300       818.958231  -441.228231     441.228231
251      636.0003       990.618921  -354.618621     354.618621
6639    -734.5264      -381.883872  -352.642528     352.642528
6884     770.3520       419.808315   350.543685     350.543685
6535     -50.0980       282.444498  -332.542498     332.542498
2358    -553.6476      -231.458954  -322.188646     322.188646
263     -251.9958      -563.118935   311.123135     311.123135

In [119]:
# Características das linhas com maiores erros do modelo Random Forest otimizado
colunas_analise = [
    'Category',
    'Sub-Category',
    'Sales',
    'Quantity',
    'Discount',
    'Profit'
]

detalhes_erros_rf = df.loc[
    maiores_erros_rf.index,
    colunas_analise
].copy()

detalhes_erros_rf['Profit_previsto'] = (
    maiores_erros_rf['Profit_previsto']
)

detalhes_erros_rf['Erro_absoluto'] = (
    maiores_erros_rf['Erro_absoluto']
)

detalhes_erros_rf

,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit_previsto,Erro_absoluto
2697,Technology,Machines,22638.480,6,0.5,-1811.0784,6484.089493,8295.167893
683,Technology,Machines,7999.980,4,0.5,-3839.9904,-173.716955,3666.273445
1803,Office Supplies,Supplies,4663.736,7,0.2,-1049.3406,993.137338,2042.477938
3151,Technology,Machines,1799.994,2,0.7,-2639.9912,-1085.635201,1554.355999
5198,Office Supplies,Supplies,3930.072,3,0.2,-786.0144,548.339231,1334.353631
9165,Technology,Machines,4476.800,4,0.2,503.6400,-769.471148,1273.111148
9639,Furniture,Tables,4297.644,13,0.4,-1862.3124,-787.253871,1075.058529
4277,Technology,Machines,9099.930,7,0.0,2365.9818,3419.272023,1053.290223
509,Office Supplies,Binders,6354.950,5,0.0,3177.4750,2198.482701,978.992299
5884,Office Supplies,Supplies,4912.590,3,0.0,196.5036,1059.057286,862.553686
318,Technology,Machines,3991.980,2,0.0,1995.9900,1223.135306,772.854694
1199,Office Supplies,Binders,1088.792,4,0.8,-1850.9464,-1256.106523,594.839877
3011,Technology,Machines,2549.985,5,0.7,-3399.9800,-2805.159698,594.820302
8100,Technology,Machines,3357.600,3,0.2,377.7300,818.958231,441.228231
251,Technology,Accessories,3347.370,13,0.0,636.0003,990.618921,354.618621
6639,Furniture,Tables,1421.664,8,0.4,-734.5264,-381.883872,352.642528
6884,Furniture,Chairs,2567.840,8,0.0,770.3520,419.808315,350.543685
6535,Furniture,Bookcases,4007.840,10,0.2,-50.0980,282.444498,332.542498
2358,Furniture,Tables,1071.576,4,0.4,-553.6476,-231.458954,322.188646
263,Technology,Machines,2519.958,7,0.4,-251.9958,-563.118935,311.123135

In [120]:
# Concentração dos erros do modelo Random Forest otimizado
analise_erros_rf['Erro_quadrado'] = (
    analise_erros_rf['Erro'] ** 2
)

erro_quadrado_total_rf = (
    analise_erros_rf['Erro_quadrado'].sum()
)

top20_erro_quadrado_rf = (
    analise_erros_rf
    .nlargest(20, 'Erro_absoluto')['Erro_quadrado']
    .sum()
)

percentual_top20_rf = (
    top20_erro_quadrado_rf
    / erro_quadrado_total_rf
) * 100

percentual_top20_rf

np.float64(97.75582310486325)

In [121]:
# Quantidade de observações na base de teste
quantidade_teste = len(analise_erros_rf)

percentual_observacoes_top20 = (
    20 / quantidade_teste
) * 100

percentual_observacoes_top20

1.0005002501250626

In [122]:
# Analise quantitaiva dos dados de Sales e Profit, utilizando percentis para entender a distribuição dos dados e identificar possíveis outliers.

percentis = [0.50, 0.75, 0.90, 0.95, 0.99, 0.995, 1.00]

df[['Sales', 'Profit']].quantile(percentis)

              Sales       Profit
0.500     54.490000     8.666500
0.750    209.940000    29.364000
0.900    572.706000    89.281620
0.950    956.984245   168.470400
0.990   2481.694600   580.657882
0.995   3394.058700   843.170600
1.000  22638.480000  8399.976000

##### Treinamento de modelo para 99% das transações

In [123]:
# Limite superior para Sales no percentil 99
limite_sales_p99 = X_train['Sales'].quantile(0.99)

limite_sales_p99

np.float64(2309.917959999998)

In [124]:
# Análise das faixas de Sales
analise_faixas_rf = pd.DataFrame({
    'Sales': X_test['Sales'],
    'Profit_real': y_test,
    'Profit_previsto': y_pred_rf_final
})

analise_faixas_rf['Faixa_Sales'] = np.where(
    analise_faixas_rf['Sales'] <= limite_sales_p99,
    'Sales <= P99',
    'Sales > P99'
)

In [125]:
# Análise das métricas de regressão por faixa de Sales
resultados_faixas = []

for faixa, dados in analise_faixas_rf.groupby('Faixa_Sales'):

    metricas = calcular_metricas_regressao(
        dados['Profit_real'],
        dados['Profit_previsto']
    )

    resultados_faixas.append({
        'Faixa': faixa,
        'Quantidade': len(dados),
        **metricas
    })

resultado_faixas_rf = pd.DataFrame(resultados_faixas)

resultado_faixas_rf

,Faixa,Quantidade,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Sales <= P99,1964,12.737271,2.380889e+03,48.794355,0.837614,17.450769,8.544,121.117129
1,Sales > P99,35,759.064248,2.742130e+06,1655.937724,-0.430624,191.358580,377.730,1404.675082

 **Analise do Modelo**
1. O R² = 0,838 indica que, dentro desse subconjunto específico do teste, o modelo apresenta uma redução de aproximadamente 83,8% no erro quadrático em relação ao preditor que usa a média do Profit desse próprio grupo como referência. O 0,838 é uma **métrica diagnóstica do segmento Sales <= P99**
2. Agora temos evidência bastante forte de que **o desempenho do modelo se deteriora drasticamente na cauda superior de Sales.**
3. Nas transações de alto Sales, não temos simplesmente lucros maiores. Temos **uma variabilidade muito maior do Profit.**. Portanto, "venda alta" não significa necessariamente "lucro alto". 
4. O modelo precisa aprender uma relação muito mais complicada.

In [136]:
# Investigação da cardinalidade e a quantidade de observações por produto
produto_stats = (
    df.groupby('Product ID')
    .agg(
        Quantidade_registros=('Product ID', 'size'),
        Sales_medio=('Sales', 'mean'),
        Profit_medio=('Profit', 'mean'),
        Discount_medio=('Discount', 'mean')
    )
    .sort_values(
        'Quantidade_registros',
        ascending=False
    )
)

produto_stats.head(20)

,Quantidade_registros,Sales_medio,Profit_medio,Discount_medio
Product ID,,,,
OFF-PA-10001970,19,114.070947,52.970274,0.031579
TEC-AC-10003832,18,622.430889,110.440294,0.077778
FUR-FU-10004270,16,26.660000,7.294675,0.175000
FUR-CH-10001146,15,162.801600,7.832420,0.186667
TEC-AC-10003628,15,93.968667,35.748080,0.093333
FUR-CH-10002647,15,242.751600,15.615600,0.180000
TEC-AC-10002049,15,917.102400,295.022880,0.040000
FUR-CH-10002880,14,388.297000,-33.910100,0.185714
FUR-CH-10003774,14,297.634571,-35.937100,0.228571
OFF-PA-10002377,14,71.760857,29.663143,0.085714
FUR-FU-10001473,14,59.976857,12.594621,0.157143
OFF-BI-10001524,14,55.746857,3.536629,0.400000
OFF-BI-10004632,14,395.399500,-17.576250,0.350000
OFF-BI-10002026,14,147.773000,24.973800,0.364286
FUR-CH-10004287,13,890.213846,90.721077,0.200000
OFF-ST-10001490,13,626.017846,155.131615,0.076923
OFF-LA-10001613,13,8.728615,3.757292,0.107692
OFF-BI-10000145,13,6.288000,0.902400,0.376923
FUR-TA-10001095,13,631.466077,-14.613546,0.257692
OFF-BI-10000301,13,12.691154,0.248846,0.492308

In [127]:
produto_stats['Quantidade_registros'].describe()

count    1862.000000
mean        5.367347
std         2.666159
min         1.000000
25%         3.000000
50%         5.000000
75%         7.000000
max        19.000000
Name: Quantidade_registros, dtype: float64

In [140]:
produto_stats['Quantidade_registros'].value_counts().sort_index().head(20)

Quantidade_registros
1      91
2     171
3     208
4     286
5     290
6     252
7     199
8     155
9      80
10     54
11     29
12     21
13     12
14      7
15      4
16      1
18      1
19      1
Name: count, dtype: int64

**Quantos produtos presentes no teste também aparecem no treinamento?**

In [141]:
produtos_train = set(
    df.loc[X_train.index, 'Product ID']
)

produtos_test = set(
    df.loc[X_test.index, 'Product ID']
)

len(produtos_train), len(produtos_test)

(1831, 1217)

In [142]:
produtos_novos_test = produtos_test - produtos_train

len(produtos_novos_test)

31

In [143]:
mascara_produto_novo = (
    df.loc[X_test.index, 'Product ID']
    .isin(produtos_novos_test)
)

quantidade_transacoes_produto_novo = mascara_produto_novo.sum()

percentual_transacoes_produto_novo = (
    quantidade_transacoes_produto_novo
    / len(X_test)
) * 100

quantidade_transacoes_produto_novo, percentual_transacoes_produto_novo

(np.int64(53), np.float64(2.6513256628314155))

**"Será que o teste será cheio de produtos que o modelo nunca viu?"**
Não. Apenas 2,65% das transações do teste possuem Product ID completamente novo.

#### Novo treinamento
Tratamento apropriado no encoder, para identificar quando o produto!

In [145]:
features_produto = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Product ID',
    'Sales',
    'Quantity',
    'Discount'
]

X_produto = df[features_produto]

In [146]:
X_train_produto = X_produto.loc[X_train.index]
X_test_produto = X_produto.loc[X_test.index]

In [150]:
# definir as features categóricas relacionadas ao produto - incluindo 'Product ID' como uma feature categórica
features_categoricas_produto = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Product ID'
]
features_numericas_produto = [
    'Sales',
    'Quantity',
    'Discount'
]

In [151]:
# definir o preprocessor para as features categóricas relacionadas ao produto
print(f"X_train_produto: {X_train_produto.shape}")

print(f"X_test_produto: {X_test_produto.shape}")

print(f"X_train_produto head:\n{X_train_produto.head()}")

X_train_produto: (7995, 9)
X_test_produto: (1999, 9)
X_train_produto head:
           Ship Mode   Segment   Region         Category Sub-Category  \
4100  Standard Class  Consumer  Central  Office Supplies   Appliances
2586  Standard Class  Consumer     East  Office Supplies      Storage
9194  Standard Class  Consumer     West  Office Supplies     Supplies
2002    Second Class  Consumer    South  Office Supplies      Storage
7225  Standard Class  Consumer     West        Furniture  Furnishings

           Product ID    Sales  Quantity  Discount
4100  OFF-AP-10004655    2.264         1       0.8
2586  OFF-ST-10001476  248.570         7       0.0
9194  OFF-SU-10001664   47.992         7       0.2
2002  OFF-ST-10000563   95.940         3       0.0
7225  FUR-FU-10000073   30.800         4       0.0

In [152]:
# Novo encoder e preprocessor para as features categóricas relacionadas ao produto
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

encoder_produto = OneHotEncoder(
    handle_unknown='ignore'
)

preprocessor_produto = ColumnTransformer(
    transformers=[
        (
            'cat',
            encoder_produto,
            features_categoricas_produto
        )
    ],
    remainder='passthrough'
)

In [ ]:
# Criação do modelo Random Forest para o conjunto de dados com a feature 'Product ID'

modelo_rf_produto = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

pipeline_rf_produto = Pipeline(
    steps=[
        ('preprocessor', preprocessor_produto),
        ('modelo', modelo_rf_produto)
    ]
)

In [155]:
pipeline_rf_produto

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category',
                                                   'Product ID'])])),
                ('modelo',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [156]:
# Cross-validation para o modelo Random Forest com a feature 'Product ID'
cv_rf_produto = cross_validate(
    pipeline_rf_produto,
    X_train_produto,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True,
    n_jobs=-1
)

In [157]:
# Transformando os resultados da validação cruzada do modelo Random Forest com a feature 'Product ID' em um DataFrame
resultados_cv_rf_produto = pd.DataFrame({
    'MAE treino': -cv_rf_produto['train_neg_mean_absolute_error'],
    'MAE validação': -cv_rf_produto['test_neg_mean_absolute_error'],

    'RMSE treino': -cv_rf_produto['train_neg_root_mean_squared_error'],
    'RMSE validação': -cv_rf_produto['test_neg_root_mean_squared_error'],

    'R2 treino': cv_rf_produto['train_r2'],
    'R2 validação': cv_rf_produto['test_r2']
})

resultados_cv_rf_produto

,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação
0,7.185548,18.809956,52.829405,85.869822,0.939105,0.925305
1,6.918479,20.040297,37.854195,189.359865,0.976109,0.151788
2,6.980659,21.260799,45.811889,144.769531,0.959438,0.721574
3,7.266588,16.482125,50.143205,73.998934,0.959798,0.829240
4,7.338741,16.545465,50.375856,80.920531,0.959157,0.805508

In [159]:
# Calculo das médias e desvios padrão da validação cruzada do modelo Random Forest com a feature 'Product ID'
print("Médias:")
print(resultados_cv_rf_produto.mean())
print("\nDesvios Padrão:")
print(resultados_cv_rf_produto.std())

Médias:
MAE treino          7.138003
MAE validação      18.627728
RMSE treino        47.402910
RMSE validação    114.983737
R2 treino           0.958721
R2 validação        0.686683
dtype: float64

Desvios Padrão:
MAE treino         0.181685
MAE validação      2.115482
RMSE treino        5.905586
RMSE validação    50.265988
R2 treino          0.013124
R2 validação       0.307698
dtype: float64

**Product ID contém sinal preditivo suficiente para reduzir o erro absoluto médio, mas, com One-Hot Encoding e esse Random Forest, não melhorou o desempenho nas métricas mais sensíveis aos grandes erros.**
1. A inclusão direta de Product ID com One-Hot Encoding melhora nosso modelo segundo a métrica principal? 
Não (RF sem Product ID   → 110,65, RF + Product ID     → 114,98)

In [160]:
df[['Order Date', 'Ship Date']].head(10)

   Order Date   Ship Date
0  09-11-2013  12-11-2013
1  09-11-2013  12-11-2013
2  13-06-2013  17-06-2013
3  11-10-2012  18-10-2012
4  11-10-2012  18-10-2012
5  09-06-2011  14-06-2011
6  09-06-2011  14-06-2011
7  09-06-2011  14-06-2011
8  09-06-2011  14-06-2011
9  09-06-2011  14-06-2011

In [161]:
df[['Order Date', 'Ship Date']].dtypes

Order Date    object
Ship Date     object
dtype: object

### **Feature Engineering**
#### Adição de informação temporal poderá melhorar a capacidade preditiva?

In [162]:
# Copiando o DataFrame original para criar um novo DataFrame com features adicionais
df_features = df.copy()

In [163]:
# Convertendo as colunas 'Order Date' e 'Ship Date' para o tipo datetime, utilizando o formato '%d-%m-%Y'
df_features['Order Date'] = pd.to_datetime(
    df_features['Order Date'],
    format='%d-%m-%Y'
)

df_features['Ship Date'] = pd.to_datetime(
    df_features['Ship Date'],
    format='%d-%m-%Y'
)

In [168]:
df_features[['Order Date', 'Ship Date']].head(10)
# print(df_features[['Order Date', 'Ship Date']].dtypes)

  Order Date  Ship Date
0 2013-11-09 2013-11-12
1 2013-11-09 2013-11-12
2 2013-06-13 2013-06-17
3 2012-10-11 2012-10-18
4 2012-10-11 2012-10-18
5 2011-06-09 2011-06-14
6 2011-06-09 2011-06-14
7 2011-06-09 2011-06-14
8 2011-06-09 2011-06-14
9 2011-06-09 2011-06-14

In [175]:
# df_features['Order_Year'] = df_features['Order Date'].dt.year
df_features[['Order Date', 'Order_Year']].head(10)

  Order Date  Order_Year
0 2013-11-09        2013
1 2013-11-09        2013
2 2013-06-13        2013
3 2012-10-11        2012
4 2012-10-11        2012
5 2011-06-09        2011
6 2011-06-09        2011
7 2011-06-09        2011
8 2011-06-09        2011
9 2011-06-09        2011

In [177]:
df_features['Order_Year'].value_counts().sort_index()

Order_Year
2011    1993
2012    2102
2013    2580
2014    3319
Name: count, dtype: int64

* Adicionar o ano do pedido melhora a capacidade do Random Forest de prever Profit?

In [178]:
# Definindo as features temporais para o modelo
features_temporal = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Sales',
    'Quantity',
    'Discount',
    'Order_Year'
]

X_temporal = df_features[features_temporal]

In [183]:
# Queremos exatamente as mesmas observações utilizadas anteriormente no treino e no teste. Assim, a única alteração do experimento será
# a inclusão da feature temporal 'Order_Year' no modelo.
X_train_temporal = X_temporal.loc[X_train.index]
X_test_temporal = X_temporal.loc[X_test.index]
print('X_train_temporal:', X_train_temporal.shape)
print('X_test_temporal:', X_test_temporal.shape)

print('X_train_temporal:')
X_train_temporal.head()

X_train_temporal: (7995, 9)
X_test_temporal: (1999, 9)
X_train_temporal:

,Ship Mode,Segment,Region,Category,Sub-Category,Sales,Quantity,Discount,Order_Year
4100,Standard Class,Consumer,Central,Office Supplies,Appliances,2.264,1,0.8,2014
2586,Standard Class,Consumer,East,Office Supplies,Storage,248.570,7,0.0,2014
9194,Standard Class,Consumer,West,Office Supplies,Supplies,47.992,7,0.2,2011
2002,Second Class,Consumer,South,Office Supplies,Storage,95.940,3,0.0,2014
7225,Standard Class,Consumer,West,Furniture,Furnishings,30.800,4,0.0,2013

In [187]:
""" Irei manter a feature Order_Year como numerica. A decisão de manter a feature como numérica é baseada na suposição de que o ano do pedido pode ter um impacto linear no lucro (Profit).
Por exemplo, pode-se esperar que, com o tempo, as estratégias de vendas e marketing melhorem, resultando em um aumento gradual no lucro. 
Além disso, tratar o ano como uma variável contínua permite capturar tendências ao longo do tempo, enquanto tratá-lo como categórico poderia perder essa informação temporal.
É arvores trabalham bem com variáveis numéricas e podem capturar relações não lineares, então manter o ano como numérico pode ser benéfico para o modelo """

features_numericas_temporal = [
    'Sales',
    'Quantity',
    'Discount',
    'Order_Year'
]
features_categoricas_temporal = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

In [189]:
# Criação do pré-processador para o conjunto de dados com a feature temporal 'Order_Year'
encoder_temporal = OneHotEncoder(
    handle_unknown='ignore'
)

preprocessor_temporal = ColumnTransformer(
    transformers=[
        (
            'cat',
            encoder_temporal,
            features_categoricas_temporal
        )
    ],
    remainder='passthrough'
)

In [190]:
# Criação do modelo Random Forest para o conjunto de dados com a feature temporal 'Order_Year'

modelo_rf_temporal = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

pipeline_rf_temporal = Pipeline(
    steps=[
        ('preprocessor', preprocessor_temporal),
        ('modelo', modelo_rf_temporal)
    ]
)

pipeline_rf_temporal

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [191]:
# Cross-validation para o modelo Random Forest com a feature temporal 'Order_Year'
cv_rf_temporal = cross_validate(
    pipeline_rf_temporal,
    X_train_temporal,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True,
    n_jobs=-1
)

In [192]:
# Transformando os resultados da validação cruzada do modelo Random Forest com a feature temporal 'Order_Year' em um DataFrame
resultado_cv_temporal = pd.DataFrame({
    'MAE_train': -cv_rf_temporal['train_neg_mean_absolute_error'],
    'MAE_val': -cv_rf_temporal['test_neg_mean_absolute_error'],

    'RMSE_train': -cv_rf_temporal['train_neg_root_mean_squared_error'],
    'RMSE_val': -cv_rf_temporal['test_neg_root_mean_squared_error'],

    'R2_train': cv_rf_temporal['train_r2'],
    'R2_val': cv_rf_temporal['test_r2']
})

resultado_cv_temporal

   MAE_train    MAE_val  RMSE_train    RMSE_val  R2_train    R2_val
0   7.643192  20.202804   52.017386   97.732228  0.940963  0.903242
1   7.102998  21.501668   34.870304  180.653437  0.979727  0.227994
2   7.327863  22.009259   44.694664  140.831795  0.961392  0.736515
3   7.578118  17.471202   46.666914   70.894033  0.965179  0.843269
4   8.070769  17.023331   53.981579   63.288106  0.953101  0.881033

In [194]:
# Calculo das médias e desvios padrão da validação cruzada do modelo Random Forest com a feature temporal 'Order_Year'
print("Médias:")
print(resultado_cv_temporal.mean())
print("\nDesvios Padrão:")
print(resultado_cv_temporal.std())

Médias:
MAE_train       7.544588
MAE_val        19.641653
RMSE_train     46.446169
RMSE_val      110.679920
R2_train        0.960072
R2_val          0.718410
dtype: float64

Desvios Padrão:
MAE_train      0.363897
MAE_val        2.288371
RMSE_train     7.498967
RMSE_val      49.502455
R2_train       0.014387
R2_val         0.281529
dtype: float64

* **Hipótese**: adicionar o ano do pedido poderia capturar mudanças temporais no comportamento do lucro.
* **Resultado**: a inclusão de Order_Year não apresentou melhoria nas métricas de validação cruzada. O RMSE passou de aproximadamente 110,65 para 110,68 e o R² de 0,719 para 0,718.
* **Decisão**: Order_Year isoladamente não será incorporado ao modelo final.

#### **Adicionar a Feature Engineering Order_Month**
* O mês em que uma transação ocorre contém informação útil para prever seu lucro?

In [195]:
# Adicionando a feature 'Order_Month' ao DataFrame df_features, extraindo o mês da coluna 'Order Date'.
df_features['Order_Month'] = df_features['Order Date'].dt.month

In [ ]:
# Visualização das primeiras 10 linhas das colunas 'Order Date' e 'Order_Month' do DataFrame df_features 
# df_features[['Order Date', 'Order_Month']].head(10)

# Análise da distribuição da feature 'Order_Month' no DataFrame df_features, utilizando value_counts() para contar a quantidade de ocorrências de cada mês e sort_index()
# para ordenar os resultados pelo índice (mês).
df_features['Order_Month'].value_counts().sort_index()

Order_Month
1      387
2      301
3      680
4      663
5      750
6      709
7      708
8      710
9     1386
10     817
11    1462
12    1421
Name: count, dtype: int64

* **Primeiro experimento tratando Order_Month como categórica nominal. Assim, não impomos ao modelo uma relação numérica artificial entre os meses.**

In [199]:
# Definindo as features com para o modelo com a feature temporal 'Order_Month' como variável categórica, mantendo a mesma estrutura de features utilizadas anteriormente.
features_month = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Order_Month',
    'Sales',
    'Quantity',
    'Discount'
]

X_month = df_features[features_month]

X_train_month = X_month.loc[X_train.index]
X_test_month = X_month.loc[X_test.index]

In [200]:
# Definindo as features categóricas e numéricas para o modelo com a feature temporal 'Order_Month', mantendo a mesma estrutura de features utilizadas anteriormente.
features_categoricas_month = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Order_Month'
]
features_numericas_month = [
    'Sales',
    'Quantity',
    'Discount'
]

In [201]:
encoder_month = OneHotEncoder(
    handle_unknown='ignore'
)

preprocessor_month = ColumnTransformer(
    transformers=[
        (
            'cat',
            encoder_month,
            features_categoricas_month
        )
    ],
    remainder='passthrough'
)

In [202]:
print('X_train_month:', X_train_month.shape)
print('X_test_month:', X_test_month.shape)

X_train_month.head()

X_train_month: (7995, 9)
X_test_month: (1999, 9)

,Ship Mode,Segment,Region,Category,Sub-Category,Order_Month,Sales,Quantity,Discount
4100,Standard Class,Consumer,Central,Office Supplies,Appliances,6,2.264,1,0.8
2586,Standard Class,Consumer,East,Office Supplies,Storage,7,248.570,7,0.0
9194,Standard Class,Consumer,West,Office Supplies,Supplies,11,47.992,7,0.2
2002,Second Class,Consumer,South,Office Supplies,Storage,12,95.940,3,0.0
7225,Standard Class,Consumer,West,Furniture,Furnishings,7,30.800,4,0.0

In [203]:
# Criação do modelo Random Forest para o conjunto de dados com a feature temporal 'Order_Month'
modelo_rf_month = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

pipeline_rf_month = Pipeline(
    steps=[
        ('preprocessor', preprocessor_month),
        ('modelo', modelo_rf_month)
    ]
)

pipeline_rf_month

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category',
                                                   'Order_Month'])])),
                ('modelo',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [204]:
# Cross-validation para o modelo Random Forest com a feature temporal 'Order_Month'

cv_rf_month = cross_validate(
    pipeline_rf_month,
    X_train_month,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True,
    n_jobs=-1
)

In [205]:
# Transformando os resultados da validação cruzada do modelo Random Forest com a feature temporal 'Order_Month' em um DataFrame
resultado_cv_month = pd.DataFrame({
    'MAE_train': -cv_rf_month['train_neg_mean_absolute_error'],
    'MAE_val': -cv_rf_month['test_neg_mean_absolute_error'],

    'RMSE_train': -cv_rf_month['train_neg_root_mean_squared_error'],
    'RMSE_val': -cv_rf_month['test_neg_root_mean_squared_error'],

    'R2_train': cv_rf_month['train_r2'],
    'R2_val': cv_rf_month['test_r2']
})

resultado_cv_month

   MAE_train    MAE_val  RMSE_train    RMSE_val  R2_train    R2_val
0   7.718820  20.758192   53.187352  100.041540  0.938277  0.898616
1   7.257007  21.247927   36.549364  179.800687  0.977727  0.235265
2   7.286375  22.283572   44.199875  144.559747  0.962242  0.722381
3   7.652017  17.526130   47.651347   70.052325  0.963694  0.846969
4   8.113123  17.445781   55.600741   66.301573  0.950245  0.869434

In [206]:
# Calculo das médias e desvios padrão da validação cruzada do modelo Random Forest com a feature temporal 'Order_Month'

print('Médias:')
print(resultado_cv_month.mean())

print('\nDesvios Padrão:')
print(resultado_cv_month.std())

Médias:
MAE_train       7.605468
MAE_val        19.852320
RMSE_train     47.437736
RMSE_val      112.151175
R2_train        0.958437
R2_val          0.714533
dtype: float64

Desvios Padrão:
MAE_train      0.352127
MAE_val        2.229456
RMSE_train     7.562717
RMSE_val      49.111899
R2_train       0.014898
R2_val         0.276215
dtype: float64

* **A inclusão das features temporais Order_Year e Order_Month, avaliadas separadamente por validação cruzada, não melhorou o desempenho do Random Forest. O modelo original apresentou RMSE médio de 110,65, enquanto Order_Year resultou em 110,68 e Order_Month em 112,15. Portanto, essas features foram descartadas.**

#### **Último experimento**
* O problema principal já está bem identificado: o Random Forest funciona relativamente bem na maior parte das vendas, mas algumas transações de valores muito altos concentram quase todo o erro quadrático, **1% das observações do teste respondem por cerca de 97,8% do erro quadrático total**, irei transformar ```Sales``` com ```log1p```, isso irá comprimir a escala dos valores elevados, continuamos distinguindo as transações, mas reduzimos a distância de escala.

In [207]:
# Adicionando a feature 'Sales_Log' ao DataFrame df_features, aplicando a transformação logarítmica natural (log1p) na coluna 'Sales' para lidar 
# com possíveis assimetrias na distribuição dos dados de vendas.
df_features['Sales_Log'] = np.log1p(df_features['Sales'])

In [208]:
# Visualização das primeiras 10 linhas das colunas 'Sales' e 'Sales_Log' do DataFrame df_features
df_features[['Sales', 'Sales_Log']].head(10)

      Sales  Sales_Log
0  261.9600   5.572002
1  731.9400   6.597064
2   14.6200   2.748552
3  957.5775   6.865450
4   22.3680   3.151368
5   48.8600   3.909219
6    7.2800   2.113843
7  907.1520   6.811412
8   18.5040   2.970620
9  114.9000   4.752728

In [209]:
df_features[['Sales', 'Sales_Log']].describe()

              Sales    Sales_Log
count   9994.000000  9994.000000
mean     229.858001     4.156119
std      623.245101     1.589793
min        0.444000     0.367417
25%       17.280000     2.905808
50%       54.490000     4.016203
75%      209.940000     5.351574
max    22638.480000    10.027451

In [211]:
# Calculando a assimetria (skewness) das colunas 'Sales' e 'Sales_Log' do DataFrame df_features para entender a distribuição dos dados e verificar se a 
# transformação logarítmica ajudou a reduzir a assimetria. Valor próximo de 0 indica distribuição mais simétrica, Valor positivo elevado indica cauda longa para a direita.
print(
    'Assimetria Sales:',
    df_features['Sales'].skew()
)

print(
    'Assimetria Sales_Log:',
    df_features['Sales_Log'].skew()
)

Assimetria Sales: 12.97275234181623
Assimetria Sales_Log: 0.2818086392049614

In [214]:
# Definindo as features para o modelo com a feature transformada 'Sales_Log', mantendo a mesma estrutura de features utilizadas anteriormente.
features_sales_log = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Sales_Log',
    'Quantity',
    'Discount'
]

X_sales_log = df_features[features_sales_log]

# Queremos exatamente as mesmas observações utilizadas anteriormente no treino e no teste. Assim, a única alteração do experimento será
X_train_sales_log = X_sales_log.loc[X_train.index]
X_test_sales_log = X_sales_log.loc[X_test.index]

In [215]:
# Definindo as features categóricas e numéricas para o modelo com a feature transformada 'Sales_Log', mantendo a mesma estrutura de features utilizadas anteriormente.
print('X_train_sales_log:', X_train_sales_log.shape)
print('X_test_sales_log:', X_test_sales_log.shape)

X_train_sales_log.head()

X_train_sales_log: (7995, 8)
X_test_sales_log: (1999, 8)

,Ship Mode,Segment,Region,Category,Sub-Category,Sales_Log,Quantity,Discount
4100,Standard Class,Consumer,Central,Office Supplies,Appliances,1.182953,1,0.8
2586,Standard Class,Consumer,East,Office Supplies,Storage,5.519739,7,0.0
9194,Standard Class,Consumer,West,Office Supplies,Supplies,3.891657,7,0.2
2002,Second Class,Consumer,South,Office Supplies,Storage,4.574092,3,0.0
7225,Standard Class,Consumer,West,Furniture,Furnishings,3.459466,4,0.0

In [216]:
# Criação do pré-processador para o conjunto de dados com a feature transformada 'Sales_Log'
features_categoricas_sales_log = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]
features_numericas_sales_log = [
    'Sales_Log',
    'Quantity',
    'Discount'
]

In [217]:
# Criação do encoder e preprocessor para as features categóricas relacionadas ao modelo com a feature transformada 'Sales_Log' 
encoder_sales_log = OneHotEncoder(
    handle_unknown='ignore'
)

preprocessor_sales_log = ColumnTransformer(
    transformers=[
        (
            'cat',
            encoder_sales_log,
            features_categoricas_sales_log
        )
    ],
    remainder='passthrough'
)

In [218]:
# Criação do modelo Random Forest para o conjunto de dados com a feature transformada 'Sales_Log'

modelo_rf_sales_log = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

pipeline_rf_sales_log = Pipeline(
    steps=[
        ('preprocessor', preprocessor_sales_log),
        ('modelo', modelo_rf_sales_log)
    ]
)

In [219]:
# Cross-validation para o modelo Random Forest com a feature transformada 'Sales_Log'
cv_rf_sales_log = cross_validate(
    pipeline_rf_sales_log,
    X_train_sales_log,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True,
    n_jobs=-1
)

In [220]:
# Transformando os resultados da validação cruzada do modelo Random Forest com a feature transformada 'Sales_Log' em um DataFrame
resultado_cv_sales_log = pd.DataFrame({
    'MAE_train': -cv_rf_sales_log['train_neg_mean_absolute_error'],
    'MAE_val': -cv_rf_sales_log['test_neg_mean_absolute_error'],

    'RMSE_train': -cv_rf_sales_log['train_neg_root_mean_squared_error'],
    'RMSE_val': -cv_rf_sales_log['test_neg_root_mean_squared_error'],

    'R2_train': cv_rf_sales_log['train_r2'],
    'R2_val': cv_rf_sales_log['test_r2']
})

resultado_cv_sales_log

   MAE_train    MAE_val  RMSE_train    RMSE_val  R2_train    R2_val
0   7.626398  19.692819   51.915176   95.193693  0.941195  0.908203
1   7.094226  21.241000   36.295216  178.703895  0.978036  0.244566
2   7.172404  22.122633   43.598098  145.775924  0.963263  0.717690
3   7.504386  17.465621   46.669712   73.118426  0.965175  0.833280
4   7.965879  16.941774   52.801216   62.999460  0.955129  0.882115

In [221]:
print('Médias:')
print(resultado_cv_sales_log.mean())

print('\nDesvios Padrão:')
print(resultado_cv_sales_log.std())

Médias:
MAE_train       7.472659
MAE_val        19.492769
RMSE_train     46.255883
RMSE_val      111.158280
R2_train        0.960560
R2_val          0.717171
dtype: float64

Desvios Padrão:
MAE_train      0.354003
MAE_val        2.270981
RMSE_train     6.732736
RMSE_val      49.451901
R2_train       0.013588
R2_val         0.274106
dtype: float64

* A transformação **logarítmica** funcionou muito bem para reduzir a assimetria de Sales, mas não melhorou o desempenho preditivo do Random Forest. Apenas demonstra uma lição importante: reduzir a assimetria de uma variável não implica automaticamente melhorar um modelo. Sales caiu de skewness 12,97 para 0,28, mas o Random Forest praticamente não se beneficiou disso. Isso é coerente com o funcionamento de árvores, que fazem divisões por limiares e são muito menos sensíveis à escala do que modelos baseados em distância ou certas formulações lineares.

### Random Forest otimizado com as 8 features originais será o modelo final.

In [223]:
features_finais = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Sales',
    'Quantity',
    'Discount'
]

features_categoricas_finais = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

features_numericas_finais = [
    'Sales',
    'Quantity',
    'Discount'
]

In [224]:
X_final = df[features_finais]
y_final = df['Profit']

In [225]:
X_train_final = X_final.loc[X_train.index]
X_test_final = X_final.loc[X_test.index]

y_train_final = y_train
y_test_final = y_test

In [226]:
print('X_train_final:', X_train_final.shape)
print('X_test_final:', X_test_final.shape)

print('y_train_final:', y_train_final.shape)
print('y_test_final:', y_test_final.shape)

X_train_final: (7995, 8)
X_test_final: (1999, 8)
y_train_final: (7995,)
y_test_final: (1999,)

In [227]:
encoder_final = OneHotEncoder(
    handle_unknown='ignore'
)

preprocessor_final = ColumnTransformer(
    transformers=[
        (
            'cat',
            encoder_final,
            features_categoricas_finais
        )
    ],
    remainder='passthrough'
)

In [228]:
modelo_final = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

In [229]:
pipeline_final = Pipeline(
    steps=[
        ('preprocessor', preprocessor_final),
        ('modelo', modelo_final)
    ]
)

pipeline_final

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [230]:
# Treinando o modelo final com os dados de treino
pipeline_final.fit(
    X_train_final,
    y_train_final
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [231]:
# Avaliando o modelo final na base de teste
y_pred_final = pipeline_final.predict(
    X_test_final
)

In [232]:
metricas_final = calcular_metricas_regressao(
    y_test_final,
    y_pred_final
)

metricas_final

{'MAE': 25.804526246522386,
 'MSE': 50350.47887664959,
 'RMSE': np.float64(224.38912379313217),
 'R2': -0.038472687940156014,
 'Média': np.float64(20.495677788894444),
 'Mediana': np.float64(8.69),
 'Desvio Padrão': np.float64(220.24847920729428)}

* O modelo apresentou R² de -0,038 no conjunto holdout, indicando baixa capacidade de generalização nesse conjunto e desempenho ligeiramente inferior ao baseline da média segundo o critério de erro quadrático.
* O Random Forest apresenta bom desempenho na maior parte das transações, mas falha fortemente em uma pequena região de transações de alto valor, e esses erros extremos dominam as métricas quadráticas globais.

In [234]:
# Registrando os resultados do modelo final
preprocessor_treinado = pipeline_final.named_steps['preprocessor']
nomes_features = preprocessor_treinado.get_feature_names_out()

nomes_features

array(['cat__Ship Mode_First Class', 'cat__Ship Mode_Same Day',
       'cat__Ship Mode_Second Class', 'cat__Ship Mode_Standard Class',
       'cat__Segment_Consumer', 'cat__Segment_Corporate',
       'cat__Segment_Home Office', 'cat__Region_Central',
       'cat__Region_East', 'cat__Region_South', 'cat__Region_West',
       'cat__Category_Furniture', 'cat__Category_Office Supplies',
       'cat__Category_Technology', 'cat__Sub-Category_Accessories',
       'cat__Sub-Category_Appliances', 'cat__Sub-Category_Art',
       'cat__Sub-Category_Binders', 'cat__Sub-Category_Bookcases',
       'cat__Sub-Category_Chairs', 'cat__Sub-Category_Copiers',
       'cat__Sub-Category_Envelopes', 'cat__Sub-Category_Fasteners',
       'cat__Sub-Category_Furnishings', 'cat__Sub-Category_Labels',
       'cat__Sub-Category_Machines', 'cat__Sub-Category_Paper',
       'cat__Sub-Category_Phones', 'cat__Sub-Category_Storage',
       'cat__Sub-Category_Supplies', 'cat__Sub-Category_Tables',
       'remainder__Sales', 'remainder__Quantity', 'remainder__Discount'],
      dtype=object)

In [236]:
# Comparando a quantidade de features originais com a quantidade de features após o pré-processamento
print('Features originais:', X_train_final.shape[1])
print('Features após preprocessing:', len(nomes_features))

Features originais: 8
Features após preprocessing: 34

In [ ]:
# Extraindo as importâncias das features do modelo Random Forest treinado
modelo_rf_final = pipeline_final.named_steps['modelo']
importancias = modelo_rf_final.feature_importances_
print('Quantidade de nomes:', len(nomes_features))
print('Quantidade de importâncias:', len(importancias))

Quantidade de nomes: 34
Quantidade de importâncias: 34

In [241]:
# Criando um DataFrame com os nomes das features e suas respectivas importâncias
df_importancias = pd.DataFrame({'Feature': nomes_features,'Importancia': importancias})
df_importancias = df_importancias.sort_values(by='Importancia',ascending=False).reset_index(drop=True)

df_importancias

                          Feature  Importancia
0                remainder__Sales     0.745064
1             remainder__Discount     0.162252
2             remainder__Quantity     0.012870
3       cat__Sub-Category_Binders     0.009285
4         cat__Category_Furniture     0.006698
5       cat__Sub-Category_Copiers     0.006500
6          cat__Segment_Corporate     0.004794
7      cat__Sub-Category_Supplies     0.004448
8             cat__Region_Central     0.004398
9        cat__Category_Technology     0.003604
10     cat__Sub-Category_Machines     0.003560
11          cat__Segment_Consumer     0.003466
12  cat__Ship Mode_Standard Class     0.003429
13               cat__Region_West     0.003400
14      cat__Sub-Category_Storage     0.003369
15  cat__Category_Office Supplies     0.003311
16              cat__Region_South     0.003196
17    cat__Ship Mode_Second Class     0.002637
18     cat__Ship Mode_First Class     0.002590
19               cat__Region_East     0.002364
20       cat__Sub-Category_Tables     0.001875
21       cat__Segment_Home Office     0.001359
22   cat__Sub-Category_Appliances     0.001347
23       cat__Sub-Category_Phones     0.001096
24    cat__Sub-Category_Bookcases     0.000684
25  cat__Sub-Category_Accessories     0.000614
26       cat__Sub-Category_Chairs     0.000562
27        cat__Ship Mode_Same Day     0.000489
28        cat__Sub-Category_Paper     0.000430
29  cat__Sub-Category_Furnishings     0.000113
30    cat__Sub-Category_Envelopes     0.000078
31       cat__Sub-Category_Labels     0.000066
32          cat__Sub-Category_Art     0.000050
33    cat__Sub-Category_Fasteners     0.000002

In [242]:
# Calculando a soma das importâncias das features para verificar se totaliza 1.0 (ou próximo disso, devido a arredondamentos)
print('Soma das importâncias:', importancias.sum())

Soma das importâncias: 1.0