In [1]:
import pandas as pd
import numpy as np
import seaborn as srn
import matplotlib.pyplot as plt

In [2]:
from charset_normalizer import from_path
caminho = "../data/raw/Superstore.csv"
resultado = from_path(caminho).best()
encoding_detectado = resultado.encoding
confianca = resultado.coherence
print(encoding_detectado)
print(confianca)

cp1250
0.7082

In [3]:
df = pd.read_csv("../data/raw/Superstore.csv", encoding= 'cp1250')

In [4]:
df.shape

(9994, 21)

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [7]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

# Objetivo Prever o lucro esperado de uma transação a partir das características comerciais conhecidas da venda.

In [8]:
df["Country"].value_counts()

Country
United States    9994
Name: count, dtype: int64

In [9]:
df.nunique() #valores únicos de todas as colunas

Row ID           9994
Order ID         5009
Order Date       1238
Ship Date        1334
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              531
State              49
Postal Code       631
Region              4
Product ID       1862
Category            3
Sub-Category       17
Product Name     1841
Sales            5825
Quantity           14
Discount           12
Profit           7287
dtype: int64

In [10]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [11]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].corr()

             Sales  Quantity  Discount    Profit
Sales     1.000000  0.200795 -0.028190  0.479064
Quantity  0.200795  1.000000  0.008623  0.066253
Discount -0.028190  0.008623  1.000000 -0.219487
Profit    0.479064  0.066253 -0.219487  1.000000

In [12]:
features = [
    "Ship Mode",
    'Segment',
    'Region',
    'Category',
    'Sub-Category',
    'Sales',
    'Quantity',
    'Discount'
    ] 

target =  'Profit'

In [13]:
X = df[features] # variáveis independentes/preditoras
y = df[target] #variável dependente/alvo

In [14]:
X.shape
y.shape

(9994,)

#### Separação de features por tipo

In [15]:
features_numericas = [
    'Sales',
    'Quantity',
    'Discount'
]

features_categoricas = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

In [16]:
print(X.head())
print(X.shape)
print(y.head()) 
print(y.shape) 
print(X.dtypes)

        Ship Mode    Segment Region         Category Sub-Category     Sales  \
0    Second Class   Consumer  South        Furniture    Bookcases  261.9600
1    Second Class   Consumer  South        Furniture       Chairs  731.9400
2    Second Class  Corporate   West  Office Supplies       Labels   14.6200
3  Standard Class   Consumer  South        Furniture       Tables  957.5775
4  Standard Class   Consumer  South  Office Supplies      Storage   22.3680

   Quantity  Discount
0         2      0.00
1         3      0.00
2         2      0.00
3         5      0.45
4         2      0.20
(9994, 8)
0     41.9136
1    219.5820
2      6.8714
3   -383.0310
4      2.5164
Name: Profit, dtype: float64
(9994,)
Ship Mode        object
Segment          object
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
dtype: object

#### Importação de bibliotecas scikit-learn > train_test_split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
# 
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [19]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (7995, 8)
X_test: (1999, 8)
y_train: (7995,)
y_test: (1999,)

In [20]:
X_train['Segment'].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

#### Criação do One_hot_encoder

In [21]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

features_numericas = [
    'Sales',
    'Quantity',
    'Discount'
]

features_categoricas = [
    'Ship Mode',
    'Segment',
    'Region',
    'Category',
    'Sub-Category'
]

encoder = OneHotEncoder(
    handle_unknown='ignore'
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            encoder,
            features_categoricas
        )
    ],
    remainder='passthrough'
)

In [22]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Ship Mode', 'Segment', 'Region', 'Category',
                                  'Sub-Category'])])

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

modelo_lr = LinearRegression()

pipeline_lr = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_lr)
    ]
)

pipeline_lr.fit(X_train, y_train)

y_pred_lr = pipeline_lr.predict(X_test)

In [24]:
print(y_pred_lr[:10])

[  79.03485168   36.24686834   55.75657936  -51.62315952 -153.79443364
    1.41577812  -14.23549171   95.41024949  -80.36007     -69.61534622]

In [25]:
comparacao = pd.DataFrame({
    'Profit Real': y_test.values,
    'Profit Previsto': y_pred_lr
})

comparacao.head(10)

   Profit Real  Profit Previsto
0      21.1428        79.034852
1      11.4600        36.246868
2      17.1580        55.756579
3     -15.1470       -51.623160
4      -6.4233      -153.794434
5       8.6744         1.415778
6     -73.7061       -14.235492
7       8.6900        95.410249
8     -15.0800       -80.360070
9      17.9080       -69.615346

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [27]:
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"MAE:  {mae_lr:.2f}")
print(f"RMSE: {rmse_lr:.2f}")
print(f"R²:   {r2_lr:.4f}")

print()
print(f"Média Profit teste:   {y_test.mean():.2f}")
print(f"Mediana Profit teste: {y_test.median():.2f}")
print(f"Desvio padrão:        {y_test.std():.2f}")

MAE:  67.76
RMSE: 282.51
R²:   -0.6461

Média Profit teste:   20.50
Mediana Profit teste: 8.69
Desvio padrão:        220.25

In [28]:
from visualizacao.resultado import calcular_metricas_regressao
from modelagem.metricas import registrar_resultado

In [29]:
resultados = pd.DataFrame()

In [30]:
resultados = pd.DataFrame()

metricas_Lr = calcular_metricas_regressao(y_test, y_pred_lr)

In [31]:
resultados = registrar_resultado(resultados, 'Regressão Linear', metricas_Lr)

In [32]:
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.495678,8.69,220.248479

#### Arvore de decisão

In [33]:
# Importação da biblioteca DecisionTreeRegressor do scikit-learn
from sklearn.tree import DecisionTreeRegressor

In [34]:
# modelo sem poda explicita, avaliação de overfitting, sem regularização, sem poda, sem limite de profundidade, sem limite de folhas, sem limite de amostras mínimas por folha
modelo_dt = DecisionTreeRegressor(random_state=42)

#Criação do pipeline para o modelo de árvore de decisão
pipeline_dt = Pipeline(
    steps=[
        ('processor', preprocessor),
        ('modelo', modelo_dt)
    ]
)

In [35]:
# Treinamento do modelo de árvore de decisão
pipeline_dt.fit(X_train, y_train)

Pipeline(steps=[('processor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo', DecisionTreeRegressor(random_state=42))])

In [36]:
# Previsão dos valores de Profit para o conjunto de teste usando o modelo de árvore de decisão
y_pred_dt_train = pipeline_dt.predict(X_train)
y_pred_dt = pipeline_dt.predict(X_test)
# Métricas
metricas_dt_train = calcular_metricas_regressao(
    y_train,
    y_pred_dt_train
)
resultados = registrar_resultado(
    resultados,
    "Decision Tree _ train",
    metricas_dt_train
)
metricas_dt = calcular_metricas_regressao(
    y_test,
    y_pred_dt
)
resultados = registrar_resultado(
    resultados,
    "Decision Tree test",
    metricas_dt
)
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.495678,8.690,220.248479
1,Decision Tree _ train,0.055392,0.911667,0.954812,0.999984,30.697456,8.636,237.603758
2,Decision Tree test,34.614556,81762.376829,285.941212,-0.686339,20.495678,8.690,220.248479

In [37]:
# Modelo com profundidade máxima dentro de uma variavel com um for, sem limite de folhas, sem limite de amostras mínimas por folha
profundidades = [2, 3, 5, 7, 10, 15, 20]
resultados_profundidade = []

for profundidade in profundidades:

    modelo = DecisionTreeRegressor(
        max_depth=profundidade,
        random_state=42
    )

    pipeline = Pipeline(
        steps=[
            ('preprocessor', preprocessor),
            ('modelo', modelo)
        ]
    )

    pipeline.fit(X_train, y_train)

    pred_train = pipeline.predict(X_train)
    pred_test = pipeline.predict(X_test)

    metricas_train = calcular_metricas_regressao(
        y_train,
        pred_train
    )

    metricas_test = calcular_metricas_regressao(
        y_test,
        pred_test
    )

    resultados_profundidade.append({
        'max_depth': profundidade,

        'MAE treino': metricas_train['MAE'],
        'MAE teste': metricas_test['MAE'],

        'RMSE treino': metricas_train['RMSE'],
        'RMSE teste': metricas_test['RMSE'],

        'R2 treino': metricas_train['R2'],
        'R2 teste': metricas_test['R2']
    })

In [38]:
# o trade-off entre viés e variância
df_profundidade = pd.DataFrame(resultados_profundidade)

df_profundidade

,max_depth,MAE treino,MAE teste,RMSE treino,RMSE teste,R2 treino,R2 teste
0,2,52.590749,65.640738,163.487234,307.807614,0.526505,-0.954115
1,3,56.364983,71.967801,133.188628,317.571728,0.685745,-1.080057
2,5,35.638830,52.029897,87.088817,289.849862,0.865639,-0.732757
3,7,22.940175,40.370094,55.892123,285.655751,0.944659,-0.682974
4,10,13.972520,35.926058,32.009010,285.275899,0.981849,-0.678501
5,15,5.015065,33.857614,12.877652,285.515430,0.997062,-0.681321
6,20,1.451083,34.609411,5.690429,288.465886,0.999426,-0.716249

* Cross-Validation

In [39]:
# Importação de bibliotecas cross validation
from sklearn.model_selection import cross_validate

modelo_dt_cv = DecisionTreeRegressor(
    max_depth=10,
    random_state=42
)

pipeline_dt_cv = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_dt_cv)
    ]
)


# Validação cruzada com 5 folds, utilizando as métricas MAE, RMSE e R², retornando também o score de treino 

cv_resultados = cross_validate(
    pipeline_dt_cv,
    X_train,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True
)

In [40]:
# Resultados da validação cruzada
# cv_resultados.keys()
# cv_resultados.items()

cv_df = pd.DataFrame({
    'Fold': range(1, 6),

    'MAE treino':
        -cv_resultados['train_neg_mean_absolute_error'],

    'MAE validação':
        -cv_resultados['test_neg_mean_absolute_error'],

    'RMSE treino':
        -cv_resultados['train_neg_root_mean_squared_error'],

    'RMSE validação':
        -cv_resultados['test_neg_root_mean_squared_error'],

    'R2 treino':
        cv_resultados['train_r2'],

    'R2 validação':
        cv_resultados['test_r2']
})

cv_df

,Fold,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação
0,1,13.360797,28.716191,30.608962,174.772580,0.979558,0.690574
1,2,13.718210,25.140158,30.287959,171.127096,0.984705,0.307267
2,3,13.319781,25.996841,29.234613,130.013412,0.983482,0.775440
3,4,13.316284,23.052769,29.152690,87.494804,0.986411,0.761274
4,5,18.129309,26.491915,39.855824,87.143652,0.974434,0.774443

In [41]:
print("cv_df mean".upper())
print(cv_df.mean(numeric_only=True))
print("___________________________________________________________")
print("cv_df std".upper())
print(cv_df.std(numeric_only=True))

CV_DF MEAN
Fold                3.000000
MAE treino         14.368876
MAE validação      25.879575
RMSE treino        31.828010
RMSE validação    130.110309
R2 treino           0.981718
R2 validação        0.661800
dtype: float64
___________________________________________________________
CV_DF STD
Fold               1.581139
MAE treino         2.108850
MAE validação      2.059895
RMSE treino        4.532844
RMSE validação    42.834914
R2 treino          0.004790
R2 validação       0.201258
dtype: float64

In [42]:
# Na base de teste.
profundidades = [2, 3, 5, 7, 10, 15, 20]
resultados_cv_depth = []
for profundidade in profundidades:

    modelo = DecisionTreeRegressor(
        max_depth=profundidade,
        random_state=42
    )

    pipeline = Pipeline(
        steps=[
            ('preprocessor', preprocessor),
            ('modelo', modelo)
        ]
    )

    cv = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=5,
        scoring=[
            'neg_mean_absolute_error',
            'neg_root_mean_squared_error',
            'r2'
        ],
        return_train_score=True
    )

    resultados_cv_depth.append({
        'max_depth': profundidade,

        'MAE treino':
            -cv['train_neg_mean_absolute_error'].mean(),

        'MAE validação':
            -cv['test_neg_mean_absolute_error'].mean(),

        'RMSE treino':
            -cv['train_neg_root_mean_squared_error'].mean(),

        'RMSE validação':
            -cv['test_neg_root_mean_squared_error'].mean(),

        'R2 treino':
            cv['train_r2'].mean(),

        'R2 validação':
            cv['test_r2'].mean(),

        'R2 validação std':
            cv['test_r2'].std()
    })

In [43]:
df_cv_depth = pd.DataFrame(resultados_cv_depth)

df_cv_depth

,max_depth,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação,R2 validação std
0,2,52.649722,54.500200,162.559645,176.684186,0.523029,0.335993,0.305824
1,3,55.274917,59.045371,133.737074,169.805431,0.679307,0.422373,0.149475
2,5,38.879173,42.824155,92.917080,138.766547,0.844241,0.584405,0.206332
3,7,24.988390,32.304489,59.049831,131.638950,0.936942,0.664059,0.133424
4,10,14.368876,25.879575,31.828010,130.110309,0.981718,0.661800,0.180011
5,15,5.236175,23.799544,13.667088,126.672710,0.996625,0.666022,0.222603
6,20,1.447648,22.873856,5.373775,108.381546,0.999483,0.734643,0.218466

In [44]:
print(f"cv['R2 validação'].std(): {cv_df['R2 validação'].std()}")
print("____________________________________________________________")
print(f"cv['test_r2'].std(): {cv['test_r2'].std()}".upper())

cv['R2 validação'].std(): 0.2012582598349565
____________________________________________________________
CV['TEST_R2'].STD(): 0.2184656979934817

In [45]:
df_cv_depth

,max_depth,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação,R2 validação std
0,2,52.649722,54.500200,162.559645,176.684186,0.523029,0.335993,0.305824
1,3,55.274917,59.045371,133.737074,169.805431,0.679307,0.422373,0.149475
2,5,38.879173,42.824155,92.917080,138.766547,0.844241,0.584405,0.206332
3,7,24.988390,32.304489,59.049831,131.638950,0.936942,0.664059,0.133424
4,10,14.368876,25.879575,31.828010,130.110309,0.981718,0.661800,0.180011
5,15,5.236175,23.799544,13.667088,126.672710,0.996625,0.666022,0.222603
6,20,1.447648,22.873856,5.373775,108.381546,0.999483,0.734643,0.218466

* GridSearchCV

In [48]:
# Importação da biblioteca GridSearchCV do scikit-learn
from sklearn.model_selection import GridSearchCV

In [47]:
# Definição do modelo de árvore de decisão

modelo_dt_grid = DecisionTreeRegressor(
    random_state=42
)

pipeline_dt_grid = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_dt_grid)
    ]
)

# Definição dos hiperparâmetros a serem testados no GridSearchCV
param_grid = {
    'modelo__max_depth': [5, 10, 15, 20, None],
    'modelo__min_samples_split': [2, 5, 10],
    'modelo__min_samples_leaf': [1, 2, 5, 10]
}

In [50]:
# Criando o objeto GridSearchCV
grid_dt = GridSearchCV(
    estimator=pipeline_dt_grid,
    param_grid=param_grid,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1,
    return_train_score=True
)

# Estimador
estimator=pipeline_dt_grid

# param_grid
param_grid=param_grid

# Scoring
scoring='neg_root_mean_squared_error'

In [59]:
# Treinando o modelo com GridSearchCV
grid_dt.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Ship '
                                                                          'Mode',
                                                                          'Segment',
                                                                          'Region',
                                                                          'Category',
                                                                          'Sub-Category'])])),
                                       ('modelo',
                                        DecisionTreeRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'modelo__max_depth': [5, 10, 15, 20, None],
                         'modelo__min_samples_leaf': [1, 2, 5, 10],
                         'modelo__min_samples_split': [2, 5, 10]},
             return_train_score=True, scoring='neg_root_mean_squared_error')

In [61]:
# Comparando combinações de hiperparâmetros
print(grid_dt.best_params_)
print("____________________________________________________________")
print(-grid_dt.best_score_)
print("____________________________________________________________")
melhor_dt = grid_dt.best_estimator_
print(melhor_dt)
# print("____________________________________________________________")
# print(melhor_dt.predict(X_test))

{'modelo__max_depth': 20, 'modelo__min_samples_leaf': 1, 'modelo__min_samples_split': 2}
____________________________________________________________
108.38154555023539
____________________________________________________________
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo',
                 DecisionTreeRegressor(max_depth=20, random_state=42))])

In [72]:
# Refinamento do modelo de árvore de decisão com os melhores hiperparâmetros encontrados pelo GridSearchCV
param_grid_refinado = {
    'modelo__max_depth': [15, 20, 25, 30, None],
    'modelo__min_samples_split': [2, 3, 5],
    'modelo__min_samples_leaf': [1, 2, 3]
}

grid_dt_refinado = GridSearchCV(
    estimator=pipeline_dt_grid,
    param_grid=param_grid_refinado,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1,
    return_train_score=True
)

In [73]:
# Treinando o modelo refinado com GridSearchCV
grid_dt_refinado.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Ship '
                                                                          'Mode',
                                                                          'Segment',
                                                                          'Region',
                                                                          'Category',
                                                                          'Sub-Category'])])),
                                       ('modelo',
                                        DecisionTreeRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'modelo__max_depth': [15, 20, 25, 30, None],
                         'modelo__min_samples_leaf': [1, 2, 3],
                         'modelo__min_samples_split': [2, 3, 5]},
             return_train_score=True, scoring='neg_root_mean_squared_error')

In [74]:
# Obtenção dos melhores hiperparâmetros do modelo refinado
print(grid_dt_refinado.best_params_)
print("____________________________________________________________")
print(-grid_dt_refinado.best_score_)

{'modelo__max_depth': 20, 'modelo__min_samples_leaf': 1, 'modelo__min_samples_split': 2}
____________________________________________________________
108.38154555023539

In [75]:
# Recuperando o melhor modelo refinado
melhor_dt = grid_dt_refinado.best_estimator_

# Validando o modelo refinado na base de teste
y_pred_dt_final = melhor_dt.predict(X_test)

# Métricas do modelo refinado
metricas_dt_final = calcular_metricas_regressao(
    y_test,
    y_pred_dt_final
)

metricas_dt_final

{'MAE': 34.60941104291444,
 'MSE': 83212.56723903443,
 'RMSE': np.float64(288.46588574567085),
 'R2': -0.7162493842972399,
 'Média': np.float64(20.495677788894444),
 'Mediana': np.float64(8.69),
 'Desvio Padrão': np.float64(220.24847920729428)}

In [76]:
# Registrando os resultados do modelo refinado
resultados = registrar_resultado(
    resultados,
    'Decision Tree Otimizada',
    metricas_dt_final
)
resultados

,Modelo,MAE,MSE,RMSE,R2,Média,Mediana,Desvio Padrão
0,Regressão Linear,67.756682,79810.828375,282.508103,-0.646089,20.495678,8.690,220.248479
1,Decision Tree _ train,0.055392,0.911667,0.954812,0.999984,30.697456,8.636,237.603758
2,Decision Tree test,34.614556,81762.376829,285.941212,-0.686339,20.495678,8.690,220.248479
3,Decision Tree Otimizada,34.609411,83212.567239,288.465886,-0.716249,20.495678,8.690,220.248479

##### Analise de Residuos e erros!

In [82]:
analise_erros_dt = pd.DataFrame({
    'Profit_real': y_test,
    'Profit_previsto': y_pred_dt_final
})
analise_erros_dt['Erro'] = (
    analise_erros_dt['Profit_real']
    - analise_erros_dt['Profit_previsto']
)
analise_erros_dt['Erro_absoluto'] = (
    analise_erros_dt['Erro'].abs()
)

maiores_erros_dt = (
    analise_erros_dt
    .sort_values(
        'Erro_absoluto',
        ascending=False
    )
    .head(20)
)
Erro = maiores_erros_dt['Profit_real'] - maiores_erros_dt['Profit_previsto']
print("Erros")
Erro
print("Maiores erros do modelo Decision Tree Otimizada:")
maiores_erros_dt

Erros
Maiores erros do modelo Decision Tree Otimizada:

      Profit_real  Profit_previsto        Erro  Erro_absoluto
2697   -1811.0784        8399.9760 -10211.0544     10211.0544
1803   -1049.3406        2504.2216  -3553.5622      3553.5622
683    -3839.9904        -509.9970  -3329.9934      3329.9934
3011   -3399.9800       -6599.9780   3199.9980      3199.9980
3151   -2639.9912         239.9960  -2879.9872      2879.9872
4277    2365.9818        4630.4755  -2264.4937      2264.4937
2492    1228.1787        2591.9568  -1363.7781      1363.7781
6014     363.9048        1453.1238  -1089.2190      1089.2190
353     1415.4296         327.5922   1087.8374      1087.8374
1438    -350.4900       -1359.9920   1009.5020      1009.5020
5198    -786.0144          83.2810   -869.2954       869.2954
251      636.0003        1416.8000   -780.7997       780.7997
8100     377.7300        1143.8910   -766.1610       766.1610
7243    -630.8820       -1359.9920    729.1100       729.1100
4128    -944.9946       -1665.0522    720.0576       720.0576
994     1276.4871         626.1850    650.3021       650.3021
509     3177.4750        2591.9568    585.5182       585.5182
7583     909.9818        1459.2000   -549.2182       549.2182
9639   -1862.3124       -1359.9920   -502.3204       502.3204
2358    -553.6476         -69.8900   -483.7576       483.7576

In [83]:
colunas_analise = [
    'Category',
    'Sub-Category',
    'Sales',
    'Quantity',
    'Discount',
    'Profit'
]

casos_extremos_dt = df.loc[
    maiores_erros_dt.index,
    colunas_analise
].copy()

In [84]:
casos_extremos_dt['Profit_previsto'] = (
    maiores_erros_dt['Profit_previsto']
)

casos_extremos_dt['Erro_absoluto'] = (
    maiores_erros_dt['Erro_absoluto']
)

In [85]:
casos_extremos_dt = casos_extremos_dt.sort_values(
    'Erro_absoluto',
    ascending=False
)

casos_extremos_dt

,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit_previsto,Erro_absoluto
2697,Technology,Machines,22638.480,6,0.5,-1811.0784,8399.9760,10211.0544
1803,Office Supplies,Supplies,4663.736,7,0.2,-1049.3406,2504.2216,3553.5622
683,Technology,Machines,7999.980,4,0.5,-3839.9904,-509.9970,3329.9934
3011,Technology,Machines,2549.985,5,0.7,-3399.9800,-6599.9780,3199.9980
3151,Technology,Machines,1799.994,2,0.7,-2639.9912,239.9960,2879.9872
4277,Technology,Machines,9099.930,7,0.0,2365.9818,4630.4755,2264.4937
2492,Technology,Phones,4548.810,7,0.0,1228.1787,2591.9568,1363.7781
6014,Technology,Phones,4158.912,8,0.2,363.9048,1453.1238,1089.2190
353,Office Supplies,Binders,4355.168,4,0.2,1415.4296,327.5922,1087.8374
1438,Furniture,Chairs,2453.430,5,0.3,-350.4900,-1359.9920,1009.5020
5198,Office Supplies,Supplies,3930.072,3,0.2,-786.0144,83.2810,869.2954
251,Technology,Accessories,3347.370,13,0.0,636.0003,1416.8000,780.7997
8100,Technology,Machines,3357.600,3,0.2,377.7300,1143.8910,766.1610
7243,Furniture,Chairs,4416.174,9,0.3,-630.8820,-1359.9920,729.1100
4128,Technology,Machines,2624.985,3,0.5,-944.9946,-1665.0522,720.0576
994,Office Supplies,Binders,2715.930,7,0.0,1276.4871,626.1850,650.3021
509,Office Supplies,Binders,6354.950,5,0.0,3177.4750,2591.9568,585.5182
7583,Technology,Phones,3499.930,7,0.0,909.9818,1459.2000,549.2182
9639,Furniture,Tables,4297.644,13,0.4,-1862.3124,-1359.9920,502.3204
2358,Furniture,Tables,1071.576,4,0.4,-553.6476,-69.8900,483.7576

#### Experimento de diagnostico das variações do erro quadratico RMSE

In [86]:
analise_erros_dt['Erro_quadrado'] = (
    analise_erros_dt['Erro'] ** 2
)
erro_quadrado_total = (
    analise_erros_dt['Erro_quadrado'].sum()
)
top20_erro_quadrado = (
    analise_erros_dt
    .nlargest(20, 'Erro_absoluto')['Erro_quadrado']
    .sum()
)
percentual_top20 = (
    top20_erro_quadrado
    / erro_quadrado_total
) * 100

percentual_top20

np.float64(97.05877554914329)

##### Modelo com Random Forest

In [87]:
# Importação da biblioteca RandomForestRegressor do scikit-learn
from sklearn.ensemble import RandomForestRegressor

In [90]:
modelo_rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)
pipeline_rf = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('modelo', modelo_rf)
    ]       
)

In [91]:
# Cross-validation para o modelo Random Forest
cv_rf = cross_validate(
    pipeline_rf,
    X_train,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True,
    n_jobs=-1
)

In [92]:
# Transformando os resultados da validação cruzada em um DataFrame
resultado_rf_cv = pd.DataFrame({
    'Fold': range(1, 6),

    'MAE treino':
        -cv_rf['train_neg_mean_absolute_error'],

    'MAE validação':
        -cv_rf['test_neg_mean_absolute_error'],

    'RMSE treino':
        -cv_rf['train_neg_root_mean_squared_error'],

    'RMSE validação':
        -cv_rf['test_neg_root_mean_squared_error'],

    'R2 treino':
        cv_rf['train_r2'],

    'R2 validação':
        cv_rf['test_r2']
})

resultado_rf_cv

,Fold,MAE treino,MAE validação,RMSE treino,RMSE validação,R2 treino,R2 validação
0,1,7.543403,19.827868,50.261266,99.399909,0.944882,0.899912
1,2,7.080873,21.297156,35.130337,179.419790,0.979423,0.238501
2,3,7.232658,22.109878,42.375497,143.387621,0.965295,0.726864
3,4,7.652364,17.583253,45.182539,74.650717,0.967359,0.826219
4,5,8.195245,17.008703,54.269317,62.983515,0.952600,0.882175

In [98]:
# Calculo das medias e desvios padrão da validação cruzada
print("***********Medias**************")
print(resultado_rf_cv.drop(columns='Fold').mean())
print("***********Desvio Padrão**************")
print(resultado_rf_cv.drop(columns='Fold').std())

***********Medias**************
MAE treino          7.540908
MAE validação      19.565372
RMSE treino        45.443791
RMSE validação    111.968311
R2 treino           0.961912
R2 validação        0.714734
dtype: float64
***********Desvio Padrão**************
MAE treino         0.432214
MAE validação      2.236506
RMSE treino        7.364577
RMSE validação    48.700495
R2 treino          0.013458
R2 validação       0.274636
dtype: float64

* Otimização do Random Forest

In [99]:
param_grid_rf = {
    'modelo__n_estimators': [100, 200],
    'modelo__max_depth': [10, 20, None],
    'modelo__min_samples_split': [2, 5],
    'modelo__min_samples_leaf': [1, 2, 5]
}

In [101]:
# Definição do grid search para o modelo Random Forest

grid_rf = GridSearchCV(
    estimator=pipeline_rf,
    param_grid=param_grid_rf,
    scoring='neg_root_mean_squared_error',
    cv=5,
    n_jobs=-1,
    return_train_score=True
)

# Treinando o modelo Random Forest com GridSearchCV
grid_rf.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Ship '
                                                                          'Mode',
                                                                          'Segment',
                                                                          'Region',
                                                                          'Category',
                                                                          'Sub-Category'])])),
                                       ('modelo',
                                        RandomForestRegressor(n_jobs=-1,
                                                              random_state=42))]),
             n_jobs=-1,
             param_grid={'modelo__max_depth': [10, 20, None],
                         'modelo__min_samples_leaf': [1, 2, 5],
                         'modelo__min_samples_split': [2, 5],
                         'modelo__n_estimators': [100, 200]},
             return_train_score=True, scoring='neg_root_mean_squared_error')

In [103]:
# Obtenção dos melhores hiperparâmetros do modelo Random Forest
print("Melhores hiperparâmetros:")
print(grid_rf.best_params_)
print("Melhor estimador:")
print(grid_rf.best_estimator_)
print("Melhor pontuação:")
print(-grid_rf.best_score_)

Melhores hiperparâmetros:
{'modelo__max_depth': None, 'modelo__min_samples_leaf': 1, 'modelo__min_samples_split': 2, 'modelo__n_estimators': 200}
Melhor estimador:
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ship Mode', 'Segment',
                                                   'Region', 'Category',
                                                   'Sub-Category'])])),
                ('modelo',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])
Melhor pontuação:
110.65473357221504

In [104]:
# Otimização do modelo Random Forest com os melhores hiperparâmetros encontrados pelo GridSearchCV
melhor_rf = grid_rf.best_estimator_

# Cross-validation para o modelo Random Forest otimizado
cv_melhor_rf = cross_validate(
    melhor_rf,
    X_train,
    y_train,
    cv=5,
    scoring=[
        'neg_mean_absolute_error',
        'neg_root_mean_squared_error',
        'r2'
    ],
    return_train_score=True,
    n_jobs=-1
)

# Transformando os resultados da validação cruzada do modelo Random Forest otimizado em um DataFrame
metricas_cv_melhor_rf = pd.DataFrame({
    'MAE treino':
        -cv_melhor_rf['train_neg_mean_absolute_error'],

    'MAE validação':
        -cv_melhor_rf['test_neg_mean_absolute_error'],

    'RMSE treino':
        -cv_melhor_rf['train_neg_root_mean_squared_error'],

    'RMSE validação':
        -cv_melhor_rf['test_neg_root_mean_squared_error'],

    'R2 treino':
        cv_melhor_rf['train_r2'],

    'R2 validação':
        cv_melhor_rf['test_r2']
})

In [105]:
# Calculo das medias e desvios padrão da validação cruzada do modelo Random Forest otimizado
print("***********Medias**************")    
print(metricas_cv_melhor_rf.mean())
print("***********Desvios Padrão**************")    
print(metricas_cv_melhor_rf.std())
print("***********RMSE validação média**************")
print(metricas_cv_melhor_rf['RMSE validação'].mean())

***********Medias**************
MAE treino          7.486122
MAE validação      19.470317
RMSE treino        46.268195
RMSE validação    110.654734
R2 treino           0.960514
R2 validação        0.719095
dtype: float64
***********Desvios Padrão**************
MAE treino         0.364873
MAE validação      2.226043
RMSE treino        6.952427
RMSE validação    49.002183
R2 treino          0.013770
R2 validação       0.274215
dtype: float64
***********RMSE validação média**************
110.65473357221504